### PR TITLE
Escape stirngs passed to test-var-query

### LINKED ISSUE #1383: Test runner not finding tests with + in middle of the name
Given the following file:

```clojure
(ns app.fun-test
  (:require [clojure.test :refer [deftest is]]))

(deftest name-with+in-it
  (is true))

(deftest name-with-plus-end+
  (is true))

(deftest name-with-plus-in-it
  (is true))

(deftest +name-with-plus-start
  (is true))
```

this is the output

```
; Evaluating file: fun_test.clj
#'app.fun-test/name-with-plus-in-it
; Running test: name-with+in-it…
; No tests found. 😱, ns: 0, vars: 0
clj꞉app.fun-test꞉> 
; Evaluating file: fun_test.clj
#'app.fun-test/name-with-plus-in-it
; Running test: name-with-plus-end+…
; 1 tests finished, all passing 👍, ns: 1, vars: 1
clj꞉app.fun-test꞉> 
; Evaluating file: fun_test.clj
#'app.fun-test/name-with-plus-in-it
; Running test: name-with-plus-in-it…
; 1 tests finished, all passing 👍, ns: 1, vars: 1
clj꞉app.fun-test꞉> 
; Evaluating file: fun_test.clj
#'app.fun-test/+name-with-plus-start
; Running test: +name-with-plus-start…
```

Note, the last one hangs with the following error in the console:

```
Exception in thread "nREPL-session-f877bb99-3510-4125-81e9-6647caa1a1dd" 
java.util.regex.PatternSyntaxException: Dangling meta character '+' near index 0
+name-with-plus-end
```

The last error `+`  regex escaping fun a coworker had while searching for the test lead me to believe that there's a regex escaping issue somewhere with the `+` character.

Expected behavior is that these tests would be detected with the _Run Current Test_ command.

### PR DESCRIPTION
**Pull request by marcomorain**
## What has Changed?

Per https://github.com/clojure-emacs/cider-nrepl/issues/730, clients
should make sure that queries are escaped. We can use the
`escape-string-regexp` package, which is already in the source-tree for
this.

Also, change the call to `test-var-query` to narrow the search to just
`test?` true, and remove `search-property`, since `name` is the default
per the Cider docs.

Fixes #1383

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *You need to sign in/up at Circle CI to find the _Artifacts_ tab.*
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [x] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.

Ping @pez, @bpringe

### CODE REVIEW

**Comment by bpringe** [comment]
Thanks! I tested the vsix using tests from #1383 and it works fine now. I think this is good to go once you update the changelog.

**Comment by PEZ** [comment]
The fixes look good to me too. The only thing I wonder is if there might be differences between Java and JS regexes that come into play, but I would think that we are pretty safe using JS regex escaping.

Please update the Changelog under *Unreleased*, @marcomorain , and we'll merge this. (Just make sure not to leave a newline between the header and the list item, we have some picky regexes in the CI scripts.)

**Comment by marcomorain** [comment]
👍 [Changelog updated](https://github.com/BetterThanTomorrow/calva/pull/1405/commits/f41065642fb83bc0856e1c545724d1e1b2fc2579)

**Comment by PEZ** [comment]
We can avoid a dependency by merely doing:

```js
string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
```

From: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#escaping

WDYT?

**Comment by PEZ** [comment]
We have a pretty fat `utilities.ts` file where that can go. 😄

**Comment by marcomorain** [comment]
Updated to remove the dependency.

**Comment by PEZ** [comment]
Awesome, such a quality improvement! Thanks! ❤️

**Pull request merged**
