### PR TITLE
Only start clojure-lsp in distinct workspace roots

### LINKED ISSUE #2065: Multiple LSP processes automatically running, broken LSP features in multi-root workspaces
The recent change how the LSP server is run has lead to some issues in my multi-root workspace

[Slack thread](https://clojurians.slack.com/archives/CBE668G4R/p1675468715446929)

[Here's a minimum repro.](https://github.com/stefan-toubia/clj-repro/tree/monorepo)
This branch defines a small "monorepo" workspace with multiple projects. There's also a vscode workspace file that lists some of the projects in this repo as standalone workspace roots.

The new setting `calva.enableClojureLspOnStart` has a couple issues:

`when-workspace-opened-use-workspace-root` (default): This causes multiple LSP processes to start, one per Clojure project workspace folder.
`when-file-opened-use-furthest-project`: This does have the desirable behavior of only starting a single LSP process in the repo root, but many LSP features do not work for projects configured as their own workspace root folders (`project-a` and `project-b` in the repro). Per the status bar indicator, no LSP server is identified as running and Calva will prompt you to start LSP.

Based on comments in the slack thread, it does seem like some of the current behavior is unintentional, though it's not clear to me exactly what the intended behavior of `when-workspace-opened-use-workspace-root` was supposed to be with regard to multiple workspace roots.

### PR DESCRIPTION
**Pull request by julienvincent**
Currently when working in Calva with the `"when-workspace-opened-use-workspace-root"` setting Calva will attempt to auto-start the clojure-lsp in _all_ discovered valid clojure projects. This causes problems when both a projects root and subdirectories from that project are opened simultaneously.

To resolve this issue we skip starting the clojure-lsp for workspace folders which are decendents of already opened workspaces that have running lsp servers.

Additionally files opened in descendent workspace folders were not able to interact with lsp processes spawned for other workspace folders, even if those folders were parent directories.

This is now resolved in the client selector which removes the artificial traversal limit.

Fixes #2065

## Checklist

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [ ] Figured if the change might have some side effects and tested those as well.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
  - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
  - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [ ] Created the issue I am fixing/addressing, if it was not present.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

### CODE REVIEW

**Comment by PEZ** [comment]
Looks good. Can you add project and workspace files to the `test-data` directory with some reproduction instructions (I sometimes put such things in READMEs of the projects/workspaces there)? It will help us test this and generally be a good foundation for talking about these things.

**Comment by julienvincent** [comment]
> Looks good. Can you add project and workspace files to the `test-data` directory with some reproduction instructions (I sometimes put such things in READMEs of the projects/workspaces there)? It will help us test this and generally be a good foundation for talking about these things.

Done - added a `projects/mono-repo` folder with a minimal mono-repo structure.

**Comment by PEZ** [comment]
What's the expected behaviour when opening the mono-repo workspace?

**Comment by PEZ** [comment]
When I add a folder to the workspace I get:

```
console.ts:137 [Extension Host] LSP request "clojure/serverInfo/raw: failed Error: Internal error
    at handleResponse (/Users/pez/Projects/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:531:48)
    at processMessageQueue (/Users/pez/Projects/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:327:17)
    at Immediate.<anonymous> (/Users/pez/Projects/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:311:13)
    at processImmediate (node:internal/timers:466:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17) (at console.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:137522))
```

**Comment by PEZ** [comment]
Actually that was probably some old error. I added the `pirate-lang` project. Adding `lein-project` does not render the error. (A bit of a mystery what's up with the `pirate-lang` project...)

> What's the expected behaviour when opening the mono-repo workspace?

* When I add a folder, with a Clojure project in it, that is not part of the hierarchy of the `mono-repo` folder, the lsp-server for this added folder is started.
* When I open the workspace with this added folder still there, servers are started for the mono-repo and the added project.

I'm thinking this is what the PR says would happen. 😄

**Comment by PEZ** [comment]
I think the test-data mono-repo workspace should contain at least one folder that is not part of the mono-repo folder hierarchy, so that the behaviour can be tested by just opening the workspace.

@stefan-toubia, how does your workspace behave with the VSIX from this PR build?

**Comment by julienvincent** [comment]
> I think the test-data mono-repo workspace should contain at least one folder that is not part of the mono-repo folder hierarchy, so that the behaviour can be tested by just opening the workspace.

Done

**Comment by julienvincent** [comment]
> * When I add a folder, with a Clojure project in it, that is not part of the hierarchy of the `mono-repo` folder, the lsp-server for this added folder is started.
> * When I open the workspace with this added folder still there, servers are started for the mono-repo and the added project.
> 
> I'm thinking this is what the PR says would happen. 😄

Yes this all sounds like the intended behaviour :)

**Comment by stefan-toubia** [comment]
I've been running on this VSIX all day and everything is working very well for me. Thanks again for addressing this issue so promptly.

**Comment by julienvincent** [comment]
> I've been running on this VSIX all day and everything is working very well for me. Thanks again for addressing this issue so promptly.

Great! I'm glad this sorted it for you :)

**Comment by PEZ** [comment]
We probably should have a look at the docs too soon.

**Pull request merged**
