### PR TITLE
Add test message to test runner

### LINKED ISSUE #425: Integrated test runner does not show test message
`clojure.test/is` allows you to include a message in the test that would display in the test output if the test fails.  This would be helpful to include in the Calva says output as well.

Example:
```
(testing "Test message"
      (is (= 1 2) "Math is hard"))
```
Calva says:
```
FAIL in: upload_helpers_test.clj: 21: create-s3-key-test: Test message:
  expected: 1

  actual: (2)
```
CircleCI:
```
FAIL in upload-helpers-test/ (create-s3-key-test) (upload_helpers_test.clj:21)
Test message
Math is hard
expected: 1
  actual: (2)
```

### PR DESCRIPTION
**Pull request by stefan-toubia**
## What has Changed?

- Add test message to the test runner output
- Reformat error and failure test runner output

Closes #425 

#### Failure test
```clj
(deftest fail-test
  (testing "The test context"
    (is (= 1 2) "Math is hard")
    (is (= 1 3))))
```
```
FAIL in my-project.upload-helpers-test/fail-test (upload_helpers_test.clj:10):
The test context: Math is hard
expected: 1
  actual: (2)

FAIL in my-project.upload-helpers-test/fail-test (upload_helpers_test.clj:11):
The test context
expected: 1
  actual: (3)
```
#### Without context or message 
```clj
(deftest fail-test-2
  (is (= 1 2)))
```
```
FAIL in my-project.upload-helpers-test/fail-test-2 (upload_helpers_test.clj:14):
expected: 1
  actual: (2)
```

#### Error test
```clj
(deftest error-test
  (testing "The test context"
    (is (= (/ 1 0) 1) "The test message")))
```
```
ERROR in my-project.upload-helpers-test/error-test (line 19):
The test context: The test message
   error: java.lang.ArithmeticException: Divide by zero (Numbers.java)
expected: (= (/ 1 0) 1)
```
Note on error outputs: The file in the error result references the source of the exception (`Numbers.java`), but the line number is from the test file (`upload_helpers_test.clj`), so I moved the file to the error message line.

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [x] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)keywords.
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [x] Made sure the PR is directed at the `dev` branch (unless reasons).
- [x] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [x] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse

### CODE REVIEW

**Comment by PEZ** [comment]
Thanks!!! Looks super on the description level. We will hava a look!

Looking at the sample output I wonder if this:

```ERROR in my-project.upload-helpers-test/error-test (line 19):```

shows up as a clickable link in the output? If not, I think it could be made to do that. There are other ways to find links there, but anyway, good to be able to do it right from the output.

**Comment by stefan-toubia** [comment]
@PEZ glad to contribute!

To clarify about the clickable links in the output, this is not something that is in current Calva test runner, right?  I wasn't familiar with generating source file links, but I just did a little searching.  Based on what I've found it seems you need the full file path, which is not provided in the test results.  I just checked, neither the failure or error outputs are links.

I haven't worked on VS Code extensions before, so I'm unfamiliar with the API.  Are you aware of another solution?

**Comment by PEZ** [comment]
I don't think there is a particular API for it. But if we print the full path to the file like so:

```
/path/to/file.clj:42
```

It gets a clickable link. That said, I now see that the output is rather a namespace-qualified symbol, so it is not as easy to convert it to an absolute path as I first thought it was. Feel free to deem it out of scope for this PR. 😄

**Comment by PEZ** [comment]
I've had a look and tested this some. Looks solid and I am ready to merge, if you think it is ready, @stefan-toubia .

**Comment by stefan-toubia** [comment]
@PEZ After investigating a little more, it's a little out of scope 😅 I will keep it in mind as I make an attempt at #424 , since I'll have to dig into `NReplClient`.

I'm good to go with the current changes, let's merge!

**Pull request merged**
