### PR TITLE
Show stacktrace on test error in repl

### LINKED ISSUE #424: Integrated test runner does not show the exception stack trace
I am loving the integrated test running, it has made my workflow much more efficient, but I've been running into major problem, I cannot see the stack trace if one of my tests throw an error.  Compare this to running `circleci.test/run-tests` and I do see a stack trace, which is very helpful when developing tests or doing TDD.  It would be great to have this in the test runner!

This is a bit of a contrived example:
```
(testing "uncaught exception"
      (is (throw (Exception. "I have no stack trace"))))
```
Calva says:
```
ERROR in:upload-helpers-test: upload_helpers_test.clj, line 20: create-s3-key-test: uncaught exception:
  error: java.lang.Exception: I have no stack trace + "
  expected: (throw (Exception. "I have no stack trace"))
```
REPL terminal with CircleCI
```
ERROR in upload-helpers-test/ (create-s3-key-test) (upload_helpers_test.clj:20)
uncaught exception
expected: (throw (Exception. "something"))
  actual: java.lang.Exception: something
 at skipperlib.upload_helpers_test$fn__82210.invokeStatic (upload_helpers_test.clj:20)
    skipperlib.upload_helpers_test/fn (upload_helpers_test.clj:9)
    circleci.test$test_STAR_.invokeStatic (test.clj:74)
    circleci.test$test_STAR_.invoke (test.clj:70)
    circleci.test$test_var_STAR_$fn__2302$fn__2303$fn__2304.invoke (test.clj:91)
    clojure.test$default_fixture.invokeStatic (test.clj:687)
    clojure.test$default_fixture.invoke (test.clj:683)
    circleci.test$test_var_STAR_$fn__2302$fn__2303.invoke (test.clj:91)
    circleci.test$once_fixtures$fn__2270$fn__2271$fn__2272.invoke (test.clj:47)
    circleci.test$once_fixtures$fn__2270.invoke (test.clj:48)
    circleci.test$test_var_STAR_$fn__2302.invoke (test.clj:89)
    circleci.test$make_global_fixture$fn__2279.invoke (test.clj:55)
    circleci.test$test_var_STAR_.invokeStatic (test.clj:87)
    circleci.test$test_var_STAR_.invoke (test.clj:76)
    circleci.test$test_var.invokeStatic (test.clj:119)
    circleci.test$test_var.invoke (test.clj:103)
    circleci.test$test_all_vars.invokeStatic (test.clj:129)
    circleci.test$test_all_vars.invoke (test.clj:127)
    circleci.test$test_ns$fn__2336$fn__2337$fn__2338.invoke (test.clj:164)
    clojure.test$default_fixture.invokeStatic (test.clj:687)
    clojure.test$default_fixture.invoke (test.clj:683)
    circleci.test$once_fixtures$fn__2270.invoke (test.clj:48)
    circleci.test$test_ns$fn__2336$fn__2337.invoke (test.clj:156)
    circleci.test$make_global_fixture$fn__2279.invoke (test.clj:55)
    circleci.test$test_ns$fn__2336.invoke (test.clj:154)
    circleci.test$test_ns.invokeStatic (test.clj:153)
    circleci.test$test_ns.invoke (test.clj:131)
    circleci.test$run_selected_tests$fn__2346$iter__2347__2351$fn__2352.invoke (test.clj:190)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.boundedLength (RT.java:1788)
    clojure.lang.RestFn.applyTo (RestFn.java:130)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    circleci.test$run_selected_tests$fn__2346.invoke (test.clj:189)
    circleci.test$make_global_fixture$fn__2279.invoke (test.clj:55)
    circleci.test$run_selected_tests.invokeStatic (test.clj:188)
    circleci.test$run_selected_tests.invoke (test.clj:180)
    circleci.test$run_selected_tests.invokeStatic (test.clj:185)
    circleci.test$run_selected_tests.invoke (test.clj:180)
    circleci.test$run_tests.invokeStatic (test.clj:200)
    circleci.test$run_tests.doInvoke (test.clj:195)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    user$eval82542.invokeStatic (form-init3945100861137048195.clj:1)
    user$eval82542.invoke (form-init3945100861137048195.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:7176)
    clojure.lang.Compiler.eval (Compiler.java:7131)
    clojure.core$eval.invokeStatic (core.clj:3214)
    clojure.core$eval.invoke (core.clj:3210)
    clojure.main$repl$read_eval_print__9068$fn__9071.invoke (main.clj:414)
    clojure.main$repl$read_eval_print__9068.invoke (main.clj:414)
    clojure.main$repl$fn__9077.invoke (main.clj:435)
    clojure.main$repl.invokeStatic (main.clj:435)
    clojure.main$repl.doInvoke (main.clj:345)
    clojure.lang.RestFn.invoke (RestFn.java:1523)
    nrepl.middleware.interruptible_eval$evaluate.invokeStatic (interruptible_eval.clj:79)
    nrepl.middleware.interruptible_eval$evaluate.invoke (interruptible_eval.clj:55)
    nrepl.middleware.interruptible_eval$interruptible_eval$fn__917$fn__921.invoke (interruptible_eval.clj:142)
    clojure.lang.AFn.run (AFn.java:22)
    nrepl.middleware.session$session_exec$main_loop__1018$fn__1022.invoke (session.clj:171)
    nrepl.middleware.session$session_exec$main_loop__1018.invoke (session.clj:170)
    clojure.lang.AFn.run (AFn.java:22)
    java.lang.Thread.run (Thread.java:748)
```

### PR DESCRIPTION
**Pull request by stephendeyoung**
## What has changed?

- Add exception stacktrace to test runner output for tests that failed in error
- Will show the 'Print stacktrace' button in the repl that user can click on to see the full stacktrace

## Details

[A PR had already been raised for this a few years ago](https://github.com/BetterThanTomorrow/calva/pull/471). Given there are git conflicts I thought it was easier to simply create a new PR.

One issue with my current implementation is that if there are multiple errors only the last error will display the 'Print stacktrace' button. Is there a way of having multiple buttons after each test error?

Fixes #424

## My Calva PR Checklist

If this PR involves only documentation changes, I have:

- [ ] Read [Editing Documentation](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva#editing-documentation)
- [ ] Directed this pull request at the `published` branch.
- [ ] Built the site locally (if the changes were more involved than simple typo fixes), and verified that the site is presented as expected.
- [ ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_ (if there was is an issue for the documentation change)
  - [ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
  - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.

If this PR involves code changes, I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Added to or updated docs in this branch, if appropriate
- [ ] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
  - [x] Smoke tested the extension as such.
  - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
  - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
  - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [ ] Created the issue I am fixing/addressing, if it was not present.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Review by PEZ — COMMENTED** [review]
Thanks for doing this! ❤️ The changes look good. I've tested that it works.

ESLint seems unhappy with something. Are you running the main build task when you hack on Calva? It should have a pane where the ESLint results are showing. Let me know if you need any help with this.

**Comment by stephendeyoung** [comment]
@PEZ I've fixed that now. I will go through the remaining checklist items.

**Comment by PEZ** [comment]
I think it looks fine. Docs is not strictly necessary here. If you find the time for that you can add it as a separate update. Merging!

**Comment by stephendeyoung** [comment]
@PEZ thanks for merging this in and releasing it. Currently if more than one test fails the user will only be able to print the stacktrace for the last error that occurs. Is there a way of displaying a button for each test error or is that overkill?

**Comment by PEZ** [comment]
It's not overkill. It is also not currently prepared for that. But shouldn't be too hard to achieve, I think. Maybe we will need to keep track of the trace objects we have created and free them when a new test run is issued. And maybe not. @bpringe usually can help with that kind of decision.

**Comment by PEZ** [comment]
Also. It would be great if we tested the feature added by this PR in an integration test. Maybe that's a way to give ourselves the courage to go for the multiple stack-trace buttons.

**Comment by bpringe** [comment]
> Maybe we will need to keep track of the trace objects we have created and free them when a new test run is issued.

That sounds like a good idea to me, if we're going to be savings traces in memory.

**Pull request merged**
