### PR TITLE
[WIP] Lex quoted stuff

### LINKED ISSUE #467: Tokenization errors
@PEZ 

Something similar is happening with the `@` character. The form:
`(print @fehse)` 
will be parsed to this:
```
0: {type: "open", offset: 0, raw: "(", state: {…}}
1: {type: "id", offset: 1, raw: "print", state: {…}}
2: {type: "ws", offset: 6, raw: " ", state: {…}}
3: {type: "junk", offset: 7, raw: "@", state: {…}}
4: {type: "id", offset: 8, raw: "fehse", state: {…}}
5: {type: "close", offset: 14, raw: ")", state: {…}}
````

_Originally posted by @cfehse in https://github.com/BetterThanTomorrow/calva/issues/463#issuecomment-552852481_

### PR DESCRIPTION
**Pull request by PEZ**
## What has Changed?

- In the REPL window, syntax highlighting, and Paredit commands regarding something like ``'`'`'@'(foo)``, now considers that as one token, instead of three, as it used to.
- This also fixes how the signature help matches active parameter for an argument like this.
- _NB: It does not fix Paredit commands in the editor, because they do not use our own Paredit yet._

This is fixed such that the tokenizer now considers all combinations of the characters ``'.`~@``, in any order and with any (one-line) whitespace between as one token, together with the list, symbol, or literal they prepend. I am using this regex: ``/(['`~@][\s\r\n]*)*/``, prepended in front of the token regexes for lists, literals, etc.

It also involves a different check for valid matching pairs. Where we used to have a dictionary of opening bracket character sequences, such as `#?(` matching against list type, I now instead just check if the opening token ends with `(`, `[`, or `{` and return true for `)`, `]`, and `}`, respectively.

This fixes #467, and then some.

## My Calva PR Checklist
I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
- [x] Created the issue I am fixing/addressing, if it was not present.
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

## The Calva Team PR Checklist:
Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse

Also pinging @mseddon for sanity check, since you wrote this stuff originally. 😄

### CODE REVIEW

**Comment by cfehse** [comment]
@PEZ 

I checked the changed regex expressions for infinite matching - and they are all good. That's a first step to sanity. *gg*

**Comment by PEZ** [comment]
Thanks. I was thinking about that fix you made regarding infinite matching when I added all those Kleene stars. 😄

**Comment by cfehse** [comment]
That's why I checked it. *gg*

**Comment by PEZ** [comment]
I merged dev, and therefore, @cfehse's paredit fixes PR. Please try use this branch (or the VSIX from here) as much as you can.

**Comment by PEZ** [comment]
I'll merge this now. There is probably no better way to discover any issues with it, anyway. 😄

**Pull request merged**
