### PR TITLE
Possible to use lein aliases

### PR DESCRIPTION
**Pull request by kstehn**
let the user choose what alias to run when there are any available related to #277

### CODE REVIEW

**Comment by PEZ** [comment]
Nice progress here!

After discussions offline, let me try to summarize what we've concluded:

What to do with `main` args? (Am I right to assume that `main` is equivalent to `run` in Leiningen?).
* We could try see if the alias has main args/run and if so not provide our own, and if not add our own.
* We could just never provide our own in the presence of an alias.

**Leiningen specific**:
* We need to figure out how we want profiles to work with this. Either aliases+profiles is not supported (as it is now in this branch). Or we try to merge profiles from the alias with whatever the user selects.
* There need to be an option for ”no alias, please”.
  * Here always let the user select profiles.
* Calva should remember the aliases selection between jack-ins in the same project.

**Comment by kstehn** [comment]
So with the last two commits.

All the Leiningen Specifics should be addressed.
I made it so now that you can choose a alias and profiles if you want too.

For the clj main-args i implemented the second point. Where we dont supply any main if a alias was choosen.

**Comment by PEZ** [comment]
The Leiningen tests I've done so far seem to work. I'll try to be more creative. :smile:

For clj, after testing I see that it can't be unconditional to skip our main. Only if the alias has main args. Jack-in will always fail if there is no main at all.

**Comment by kstehn** [comment]
Okay just did it. 
I check for the selected aliases if main-opts are available. 
If calva does not supply its own main.

**Comment by PEZ** [comment]
Yeah, so I think this works now.

Nice with those docs telling about what steps are involved in cooking the command lines!

**Pull request merged**
