### PR TITLE
[Fix] Simplify build system

### LINKED ISSUE #346: [Buildsystem] Simplify build system configuration
I think the current build system configuration could be a bit simplified do make the usage easier for developers and to improve the automation in the CI/CD process. I would suggest the following changes:
- Only one watch task for development which starts both watchers concurrently. The current configuration has two tasks which must be started in a specific order. Another disadvantage of this configuration is that die output of the first task is obscured by the second task.
- Replace all relative path values in `webpack.config.js` with resolved fully qualified ones.
- Get rid of the `IS_DEV_BUILD` environment because it is only used to select which webpack package to build for development and production. Evaluate the `--mode` commandline parameter from webpack in `webpack.config.js` instead.
- Change the script configuration in `package.json` that it is possible to build the extension from a clean cloned directory only by running `npx vsce package`.

### PR DESCRIPTION
**Pull request by cfehse**
This pull request:

Fixes #346

Tested on following platform(s):
- [x] Windows
- [x] Linux
- [x] macOS

Introduces the following change(s):

`webpack.config.js`
- Added comments to make the configuration more explainable. 
- Replaced all relative path values with resolved full qualified ones.
- The selection which packages to create is changed to evaluate the webpack `--mode`parameter.

`package.json` / `.vscode/tasks.json` / `.vscode/launch.json`
- Only one build task. This is simpler and  no order of execution required.
- Using the `concurrently` module for the `watch` script allows to see the output from both watchers (`webpack` and `tsc`).
- Removed the environment `IS_DEV_BUILD` because the the webpack `--mode`parameter is now used instead (see `webpack.config.js`).
- The build is now able to build from a clean `git clone` directory by only running `npx vsce package`.

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Referenced the issue I am fixing/addressing.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.
- [ ] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

Ping: @pez, @kstehn

### CODE REVIEW

**Comment by kstehn** [comment]
That is pretty awesome.
From my side i would consider merging this. 

As a reminder the Wiki for how to Contribute should then also be updated.

**Comment by PEZ** [comment]
This is as awesome as it gets. I say add the issue and reference it and then we'll merge it.

I don't think it should be a changelog entry, though. At least, so far, we haven't logged changes to the dev an build processes there.

**Comment by PEZ** [comment]
I tested it on MacOS. Works like a charm! It is something I have wanted to achieve for so long, but have lacked the knowledge about how to do it. You are a blessing to the Calva project, @cfehse!

**Comment by cfehse** [comment]
Housekeeping is done.

Ping: @PEZ, @kstehn

**Comment by PEZ** [comment]
And now I have updated the wiki. A sweet feeling removing that extra step.

**Pull request merged**
