### PR TITLE
Fix/repl window history for Linux

### LINKED ISSUE #491: clj repl window history gets out of sync
one would expect that <alt><up-arrow> would always yield the last entered line.
In some cases, the like before is returned, and you can't get the last entered line
if you mess with it a time or two, you can *then* get the prior line
video attached (I hope)

[repl-trouble.zip](https://github.com/BetterThanTomorrow/calva/files/3907305/repl-trouble.zip)

### PR DESCRIPTION
**Pull request by bpringe**
## What has Changed?

- Added debounce to repl window functions that are mapped to alt key (whether in single- or multi-line mode). This fixes the issue on Linux where commands called with alt+up or alt+down are somehow called twice in succession.

Fixes #491 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [x] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse, @bpringe

This could use some testing before merging, but so far it works smoothly on my Ubuntu machine.

### CODE REVIEW

**Comment by PEZ** [comment]
Thanks for tackling this annoying issue!

When I try this the key repeat for the debounced commands behave strange. So pressing and holding `up` in `multi-line` mode, for instance, will move the cursor up first one line, then after a little pause, one line more. Then nothing more. If I lower the debounce to 10 msec the repeat starts to work as w/o debounce. But, of course I don't know if 10 msec is enough to help the Linux issue... Maybe there is a working compromise to be found, in any case.

**Comment by bpringe** [comment]
Hmm, I'll have to play with it more and possibly modify the debounce code. I got that from a blog post, which supposedly got it from the underscore.js library =P.

**Comment by bpringe** [comment]
The 10 ms debounce worked for me on Linux. I think this is good to go. Maybe @Gnurdle would want to test this out on his Linux system as well.

I can't get the vsix from the PR because when I try to opt-in to the new experience on CircleCI I get a 404. But I built the image locally and uploaded for sharing: https://drive.google.com/file/d/1G4WnDuvI16gNwRtBZhVGsxPDf5Fk56zC/view?usp=sharing

**Comment by PEZ** [comment]
I also get that 404. But With some clicking around I found the vsix 😄 https://3596-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.74-fix-repl-window-history-72b9a9ff.vsix

**Comment by bpringe** [comment]
How did you do that? Instructions in the wiki (being logged in, opting in to new experience) did not work for me. If what you did is repeatable by other users we could update the wiki. 😃

**Comment by Gnurdle** [comment]
Just tried it - seems to work for me as well

**Comment by PEZ** [comment]
I have already opted in. I logged in and clicked my way to the pipelines listing and found the visit that way.

**Comment by bpringe** [comment]
Oh, right! 😄 👍

**Pull request merged**
