### PR TITLE
First try for a dafault msg handler for the nrepl

### PR DESCRIPTION
**Pull request by kstehn**
This should address the issue that they are no output outside a evaluation.

Adresses the issue #218

### CODE REVIEW

**Comment by PEZ** [comment]
Cool!

Checking here. Whenever there is output ”out of band” we will print it in the REPL window. Regardless of if it is a result of an inline eval or not? We do not know here if it is an inline eval or something initiated in the REPL window, so we can't really route it ”right”, but someone like me would question using the REPL window for the output. I seldom use that window, and instead work from the editor files. Maybe it should be a setting where this kind of ”async” output should go?

**Comment by kstehn** [comment]
That is correct every time we dont find a handler for it, it gets printed.

Well why not also output it to calva says?

**Comment by PEZ** [comment]
Or there could be a separate output channel where we send all output. If it is ”within band” it also gets printed with the results.

It could even be the ”Calva Connection Log” (renamed, but just somewhere where the user knows to check for all stdout and stderr stuff ever resulting from an nREPL message...

**Comment by kstehn** [comment]
I could get behind the extra output channel.
Not sure how you feel about this, but i think it would be also nice to have it pprinted.

**Comment by PEZ** [comment]
> i think it would be also nice to have it pprinted.

Here I think that #335, that @bpringe is working on, might come in handy.

(But also, maybe stdout stuff is seldom subject to pprinting?)

**Comment by kstehn** [comment]
@bpringe 
could you test this if it fix your use case :)

**Comment by bpringe** [comment]
I'm not sure which issue of mine this would fix, but for these issues I have created it does not affect them - #218 and #327. I'm working on 327 currently.

**Comment by kstehn** [comment]
@bpringe 
it should fix #218 like i wrote in the PR message
and when i tested this with @PEZ yesterday it worked like for emacs

**Comment by bpringe** [comment]
@kstehn Sorry, I don't know what happened last time but I thought it was not working as expected, and I also missed your note about #218 up above. I now see the output in the Calva says window when I run the go-loop with println statement as in #218. I like the "Send Async Output To" setting as well! Thanks.

**Pull request merged**
