### PR TITLE
CI steps in pure docker

### PR DESCRIPTION
**Pull request by simonacca**
## What has changed?

As per [#clojurians thread](https://clojurians.slack.com/archives/CBE668G4R/p1695194417678439) this PR contains a dockerfile that helps in running the CI steps in an isolated docker environment.

Related to https://github.com/BetterThanTomorrow/calva/issues/2317

Run with `./scripts/build-and-test/run.sh step-test-integration`

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [ ] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
    - [ ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
        - [ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
        - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [ ] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Comment by PEZ** [comment]
Thank you, thank you, thank you! ❤️ 🙏

**Comment by simonacca** [comment]
If you end up finding these useful it might be worth considering setting up circleCI to use these images directly, so that they stay in sync in the long run.
At a previous job we set things up like this so as to buy into the tooling of any specific CI as little as possible and retain the ability to run most CI pipelines locally.

Haven't used circleCI personally but happy to look into this if needed.

**Comment by PEZ** [comment]
Oh, yes, that sounds fantastic. It's a huge problem today that it's so hard to run the steps locally. Takes a lot of slow-feedback trial-and-error to fix or change things.

**Comment by simonacca** [comment]
Alright! Will give it a try on a separate repo and circleCI account for the moment

**Pull request merged**
