### PR TITLE
fixed repl history for forced eval in repl file

### LINKED ISSUE #1504: 'Show Previous REPL History Entry' command not working on v.2.0.237
When in REPL window ALT + Up Arrow does not give you the previous command. It either does nothing or randomly throws a command from history at you.

Works just fine in v.2.0.235
https://clojurians.slack.com/archives/CBE668G4R/p1643273088767469

### PR DESCRIPTION
**Pull request by Cyrik**
## What has Changed?

Instead of handling `evaluateOutputWindowForm` command in a special way to add it to the history, we now check if the eval happened while we are inside the repl.
This is not ideal since it interacts in a complicated way with snippet eval inside the repl.

Fixes #1504 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
     - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [x] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.

Ping @pez, @bpringe

### CODE REVIEW

**Comment by Cyrik** [comment]
Once we have some integration tests for the eval stuff we should change the way repl code gets evaled. It should go through the same "paste into the repl file" process as the rest so we don't need special handling when inside the file.

For now this is the best fix I can come up with for hitting "ctrl+enter" or similar inside the repl window

**Comment by bpringe** [comment]
I tested this build locally and it seems to work. Thanks for the fix! If you can add another changelog entry for this change too then I think we can merge. Feel free to adjust that issue name if you want to be more specific.

**Comment by Cyrik** [comment]
done, thanks

**Comment by bpringe** [comment]
Just removed a newline in the changelog which I think may throw off our publishing script or release pipeline. Let's merge. 🚀

**Pull request merged**
