### PR TITLE
[WIP] Pretty printing does only that (not also expanding the result)

### LINKED ISSUE #378: pretty printing in repl doesn't emit reader literals
follows is the difference between pretty and non-pretty repl output
clj.user=> 
(ct/now)
#<org.joda.time.DateTime@71436076 2019-10-06T14:13:50.287Z>
clj.user=> 
(ct/now)
#clj-time/date-time "2019-10-06T14:14:22.977Z"
clj.user=>

This is not a huge(tm) deal, but it is a difference.

The particular case that annoys is trying to paste output back into a 'def' etc.

### PR DESCRIPTION
**Pull request by PEZ**
## What has Changed?
- Pretty printing is now performed using `calva-lib` on the plain-printed results from nrepl. Instead of doing it via nrepl.
- Since we need to first parse the result string in order to prettify it, there are situations when the string doesn't parse. (E.g. Datomic `:db-before` values.) In these cases we print the result plain instead and show the parsing error causing the pprint to not happen. 
- This way of doing the pprint also means data readers are left alone. Which should fix #378 
- This also avoids having values ”expanded” by pretty printing, which can get pretty hairy, as #415 shows.

To test the change, you can use this project: https://github.com/PEZ/nrepl-pprint-datomic
See #415 for the repro steps.

Fixes #378 #415

## My Calva PR Checklist
I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

## The Calva TEAM PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse

### CODE REVIEW

**Comment by kstehn** [comment]
Instead of ignoring those with literals That we cant read
Maybe supply a default literal handler to the edn Reader?
For example like here https://github.com/clojure-cookbook/clojure-cookbook/blob/master/04_local-io/4-17_unknown-reader-literals.asciidoc

**Comment by PEZ** [comment]
We're not using `read-string` here. Because that would introduce some of the problems that we are trying to avoid (e.g. #378). The strings are parsed using `rewrite-cljs`, which just emit the literals literally (pun intended 😄).

So, literals are handled fine with this change. It croaks on trying to parse the `db` values, which I think is an improvement on what's happening inside nrepl, where the whole database gets dumped.  I'll put the reproduction steps in the OP so that it will be clearer what the change is about and how to test this PR.

On the topic of default literal handler. Here's a slightly less engineered example of it put to use: https://github.com/BetterThanTomorrow/calva/blob/master/src/cljs-lib/src/calva/js_utils.cljs#L20
We use `parse-string` there because I thought it was the safest way to parse `deps.edn`, and other clojure project config files. I'm less convinced today that it is safer than using `rewrite-cljs`, but maybe something is really wrong if we find unparsable values inside those...

**Comment by PEZ** [comment]
Random thought: The reason we need to parse the `eval` result is that we get it as a string. If we could get it as EDN, then `zprint` can probably pretty print even those Datomic value references. I doubt we _can_ get the result as EDN, though, but there is an EDN nREPL transport...

**Comment by cfehse** [comment]
@PEZ 

This implementation does not work for things that worked before. Your new implementation complains about a function in the data (invalid symbol) while the old implementation simply printed the name of the function. I think the parsing is a bit to optimistic about errors - it gives up to quickly. *gg*

[pprint-2.0.52.txt](https://github.com/BetterThanTomorrow/calva/files/3751886/pprint-2.0.52.txt)
[pprint-pr-414.txt](https://github.com/BetterThanTomorrow/calva/files/3751887/pprint-pr-414.txt)

**Comment by PEZ** [comment]
That is actually an example of the problem at hand. The pretty printed version is much more than just pretty printed. It's exploded and huge. That could be a nice feature, but pretty print is a bad name.

**Comment by PEZ** [comment]
So, I think these two (from my Datomic-test repo) illustrate the problem pretty well:

* [original.txt](https://github.com/BetterThanTomorrow/calva/files/3752961/original.txt)
* [exploded.txt](https://github.com/BetterThanTomorrow/calva/files/3752962/exploded.txt)

**Comment by PEZ** [comment]
Agree it is a bit boring with the parser croaking like that. But there is not that much we can do about that...

**Comment by cfehse** [comment]
@PEZ

Are you really sure that my example is expanded in the old pretty printed version? I take a look at this tomorrow.

**Comment by PEZ** [comment]
Yeah, look at the interceptors. They only have `:name` in the original, and then when pretty printed they have more entries.

**Comment by PEZ** [comment]
I changed the title of the PR to reflect the purpose rather than the implementation. I'm exploring solutions from several angles. One is to try solve this in `cider-nrepl`. Another angle is to investigate what options we can use with pretty printers like `zprint`. So have this issue open on zprint right now: https://github.com/kkinnear/zprint/issues/111

**Pull request closed without merging**
