### PR TITLE
Improve debugger call stack

### LINKED ISSUE #1150: Add stack frames to debugger call stack
I tried calva debugger in metabase project, wherever I pause the application by Instrumenting top level form for debugging, It pauses and everythinks works as expected but call stack, code is paused in a function and I know there are at least more than 3 files involved and many functions has called each other until they have reached this function but call stack only shows current function:
image
While I want to know who called this function

### PR DESCRIPTION
**Pull request by bpringe**
## What has Changed?

- Add more stack frames besides just the current stack frame to the call stack during debugger sessions

Fixes #1150 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *You need to sign in/up at Circle CI to find the _Artifacts_ tab.*
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [x] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and tested it there if so.
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @bpringe

### CODE REVIEW

**Comment by bpringe** [comment]
@PEZ This is ready for review. I added some tests that I felt are maybe pointless, but then I figured I might as well just leave them. More tests are better anyway, right? :smile:

**Comment by bpringe** [comment]
I only tested on Linux, but I don't see there being any differences on other OS's. But feel free to test on Mac. Keep in mind if you just directly call the function you instrumented you may only see 1 stack frame.

**Comment by PEZ** [comment]
This immediately got a LOT more useful!. Quickly navigating the call chain is great!

On my first try of this, the top stack frame wasn't selected, so no variables in the sidebar and also the editor didn't scroll to focus the breakpoint.

Now I can't reproduce this fully. The frame still does not get highlighted, but the rest happens as I expect and am used to (local variables, and scroll to breakpoint).

This might be out of scope. But I would have loved if instrumenting `step2` below, then evaluating the rich comment experiment would have given me a call stack something like:

1. current-ns/step2
2. clojure.core/map
3. current-ns/step1

```clojure
(defn step2 [x]
  (->> x
      (assoc {} :x)))

(defn step1 [x]
  (map step2 x))

(comment
  (map step1 [[["foo"]]]))
```

Now it only gives me:

1. current-ns/step2

**Comment by bpringe** [comment]
>On my first try of this, the top stack frame wasn't selected, so no variables in the sidebar and also the editor didn't scroll to focus the breakpoint.

Hmm, doesn't sound good, but I don't fully understand what you mean. When the debugger started, it didn't stop at a breakpoint and highlight the line yellow in the editor?

Regarding that last part, I suppose I should also include the `clj` stack frames (such as clojure.core calls). The stacktrace given from cider-nrepl doesn't seem to include the call to `step1` though. If you want to see what is returned from cider-nrepl, place a breakpoint near the bottom of `stackTraceRequest` and then inspect `stackTraceResponse.causes[0].stacktrace`.

**Comment by PEZ** [comment]
> When the debugger started, it didn't stop at a breakpoint and highlight the line yellow in the editor?

Exactly. But only the first time. Couldn't reproduce it after that.

**Comment by PEZ** [comment]
Much better with the `clj` and `repl` frames included.

Do you think it is possible to get the local variables in each frame? I tried to figure it out but I only see the variablesRequest being called, and then we get the variables from what we have saved in the state, which is from the breakpoint frame.

**Comment by bpringe** [comment]
I'm not sure if that's possible. I still have some work to do on the call stack, but will be out this weekend. Will try to finish it up next week.

**Comment by bpringe** [comment]
Well, I noticed that the nodejs debugger does show the local variables when you click on a past call stack frame. Not sure if or how we can do that, but can look into it.

**Comment by bpringe** [comment]
@PEZ I'm ready to merge this PR once we can figure out why that test-grammar job is failing. It fails on the `Run package tests` step with this error:

```
Running specs...
/usr/share/atom/atom: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
```

I see other dependency-related issues earlier in that step:

```
Unpacking atom (1.57.0) ...
dpkg: dependency problems prevent configuration of atom:
 atom depends on libgtk-3-0 (>= 3.9.10); however:
  Package libgtk-3-0 is not installed.
 atom depends on libnotify4; however:
  Package libnotify4 is not installed.
 atom depends on libxtst6; however:
  Package libxtst6 is not installed.
 atom depends on libnss3 (>= 2:3.22); however:
  Package libnss3 is not installed.
 atom depends on xdg-utils; however:
  Package xdg-utils is not installed.
 atom depends on libxss1; however:
  Package libxss1 is not installed.

dpkg: error processing package atom (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.62) ...
Errors were encountered while processing:
 atom
 ```
 
Maybe something changed with atom that requires we manually download some other dependencies, or something changed with the container image. I'm guessing since we use `circleci/node:latest` it's not exactly a deterministic process, aside from also downloading the latest atom release.

**Pull request merged**
