### PR TITLE
Add Plain CLJS REPL sequences

### LINKED ISSUE #1114: ClojureScript browser-connected REPL without Figwheel or shadow-cljs
I wanted to have in Calva a ClojureScript browser-connected REPL for the hello-world project of ClojureScript's "Quick Start" guide (https://clojurescript.org/guides/quick-start), without using Figwheel or shadow-cljs.

AS @PEZ told me [in Clojurian's Slack #calva channel](https://clojurians.slack.com/archives/CBE668G4R/p1618053537387000), this can be achieved by adding this custom connect sequence to `.vscode/settings.json`

```
{
    "calva.replConnectSequences": [
        {
            "projectType": "deps.edn",
            "name": "plain cljs browser repl",
            "cljsType": {
                "dependsOn": "User provided",
                "connectCode": "(do (require 'cljs.repl.browser) (cider.piggieback/cljs-repl (cljs.repl.browser/repl-env)))"
            }
        }
    ]
}
```

and then jacking in with this "plain cljs browser repl". As discussed in Slack this should probably be a built-in connect sequence, and that's why I'm opening this issue, as suggested.

OTOH, in the same Slack discussion, @PEZ also provided a connect sequence that I think solves [this other issue](https://github.com/BetterThanTomorrow/calva/issues/66) about connecting to a Node.js REPL

```
{
    "calva.replConnectSequences": [
        {
            "projectType": "deps.edn",
            "name": "plain cljs node repl",
            "cljsType": {
                "dependsOn": "User provided",
                "connectCode": "(do (require 'cljs.repl.node) (cider.piggieback/cljs-repl (cljs.repl.node/repl-env)))"
            }
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by PEZ**
## What has Changed?

Adding built in REPL Connect/Jack-in sequences for Plain CLJS Browser and Node REPLs.

”Plain” here means that there is no shadow-cljs or figwheel involved.

The CLJS repl settings are named, "Plain CLJS Browser" and ”Plain CLJS Node”, respectively. Making the jack-in project type menu in a deps.edn project look like so:

image

Are these good names you think, @bpringe, @xavi?

Fixes #1114

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *You need to sign in/up at Circle CI to find the _Artifacts_ tab.*
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and tested it there if so.
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @bpringe

### CODE REVIEW

**Comment by bpringe** [comment]
I think those names are probably good. What type of repl is that considered, technically? For example, it uses standard input and output, right? I was wondering briefly if we should specify it that way, but I think "Plain" is best for newcomers who may just know that they followed a getting started guide, and for all they know it's just a "plain" repl.

**Comment by xavi** [comment]
I would name these...

deps.edn + ClojureScript built-in browser REPL
deps.edn + ClojureScript built-in Node.js REPL  (or "deps.edn + Node.js REPL", see below)

and I would put them just after deps.edn (before Figwheel and the rest of options), so that they're ordered starting with the built-in ones, which are also the most basic.

"Built-in", versus "custom", and instead of "plain", is also used in the official documentation to refer to these REPLs
https://clojurescript.org/community/custom-repls

"Built-in" is also used in this useful overview article about REPLs
https://lambdaisland.com/guides/clojure-repls/clojurescript-repls

The "Quick Start" guide (https://clojurescript.org/guides/quick-start) and `cljs.main` `--repl-env` option (https://clojurescript.org/reference/repl-and-main#_cljs_main_help) refer to  "browser" and "Node.js"/"node" REPLs, so this is consistent with that. I prefer "Node.js" to "node", it's more precise (or "narrow" as Zach Tellman says in "Elements of Clojure" :)

I am not sure about "deps.edn + ClojureScript built-in Node.js REPL". I would use that for consistency with the built-in browser REPL option, but "deps.edn + Node.js REPL" is shorter and better I think. I assume it's unambiguous, as this is the only way to get a Node.js REPL, right?

On the other hand, I think "Plain CLJS Browser" unnecessarily abbreviates ClojureScript and it's ambiguous, as it could be interpreted as a plain browser written in CLJS :)

**Comment by PEZ** [comment]
Good points. I might go with "ClojureScript Built-in for Browser/Node.js”.

I would rather not have REPL in the name, because it is not so much about the REPL as it is about the project.

About the ordering. I don't want to encourage people into the dead end that these options represent. The help that Figwheel and Shadow offers is invaluable when building with ClojureScript. The built-in options are good for quickly trying ClojureScript out, but for most people it doesn't make sense to build their first project like that, I think.

**Comment by xavi** [comment]
Ok, I understand.

Just a detail... currently Node.js (that's the correct name, https://nodejs.org/ ) is referred to in the modified docs and UI as Node, node, node.js, and Node.js. I guess no one will be confused by that :) but at the same time I think Calva will look a better product if Node.js is used everywhere.

Thanks a lot for your work on Calva and responsiveness on this issue!

**Comment by PEZ** [comment]
Agree about Node.js, but it got a bit strange to read it so I now went with lowercasing both browser and node, and actually scrapping the `.js` part, because when I added the option to the documentation I wanted something that worked good in prose. Anyway, it looks good in the menu now, I think.

Great that you highlighted the need for this option. I've been focusing on the Getting Started story lately and this was a glaring hole. Now it is quite sweet.

1. Create the small directory structure that the Quick Start tells you to
2. Jack-in

Boom!

😄

**Pull request merged**
