### PR TITLE
Consolidate commands, providers, events into collections

### LINKED ISSUE #1897: `extension.ts` can be refactored for less boilerplate registering commands
The main-entry file `src/extension.ts` has numerous duplicate calls to `context.subscriptions.push` and duplicate or nearly duplicate calls to `vscode.someScopeOrSubAPI.registerAThing`. What Calva actually provides here is buried inside the boilerplate wrappings of these individual registry calls.

I propose improving this, by gathering related functions together into a small number of collections, keyed on the feature provided (blended with whatever data is needed to determine how to dispatch). Then iterate over the collections to apply registry and disposable storage for each feature.

*-This could also potentially extend to other files with similar behavior, such as* `src/calva-fmt/src/extension.ts`*. Even if so, that is beyond the scope of this issue.*

### PR DESCRIPTION
**Pull request by skylize**
Make dictionary collecting each of Commands, Providers, and Events. Then iterate over each collection to register w/ Code and push into disposables storage.

## What has changed?

- Move commands, providers, and events into collections in extension.ts
- Iterate over the collections to register them and store disposables.

Fixes #1897

## My Calva PR Checklist

If this PR involves only documentation changes, I have:

- ~[ ] Read [Editing Documentation]~(https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva#editing-documentation)
- ~[ ] Directed this pull request at the `published` branch.~
- ~[ ] Built the site locally (if the changes were more involved than simple typo fixes), and verified that the site is presented as expected.~
- ~[ ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_ (if there was is an issue for the documentation change)~
  - ~[ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)~
  - ~[ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.~

If this PR involves code changes, I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [ ] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- ~[ ] Added to or updated docs in this branch, if appropriate~
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
  - [x] Smoke tested the extension as such.
  - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
  - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
  - ~[ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.~
- [x] Created the issue I am fixing/addressing, if it was not present.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Comment by PEZ** [comment]
It actually has never been a problem with the boilerplate here. We just add, remove and edit commands, and VS Code helps with finding the right place.

I still like where this change is going. If we skip the newlines between the command entries we can win a bit more of high level overview from it, I think. Possibly grouping them in some nice way. (I think they often are grouped like that as it is, and I also think we can do any grouping as a follow-up to this change.)

A thing to note is that we do this a bit differentlty than what we do in `src/paredit/extension.ts`. Not sure if that is a problem or totally fine. Again, we can probably think about that in a follow-up change.

**Review by PEZ — COMMENTED** [review]
Please update the changelog. Then we're pretty much good to go, imo.

**Comment by skylize** [comment]
> If we skip the newlines between the command entries we can win a bit more of high level overview from it, I think.

In agreement on removing empty lines. They were there only because it felt stylistically like a shorter leap from the existing code. The high level overview is the biggest win here in any case.

> Possibly grouping them in some nice way. (I think they often are grouped like that as it is, and I also think we can do any grouping as a follow-up to this change.)

Current grouping is haphazard and inconsistent. It reflects organic growth of the extension, more than helpful organization. I think alphabetical is a better starting point until someone takes time to break off some well-consisdered groups. Alphabetic inherently provides some natural grouping too, as related commands often start with the same prefix.

> A thing to note is that we do this a bit differentlty 

Whoops. I had a comment about that planned, but apparently forgot while switching to github.com UI instead of `gh` cli tool. It was supposed to read something like:
> This could potentially be extended to other files that register subscriptions, but that is beyond the scope of this PR.

**Comment by skylize** [comment]
I tried to rebase `dev` into this branch and made an unnecessary mess of the history. So starting over at #1906.

**Pull request closed without merging**
