### PR TITLE
Make jack-in deps versions configurable

### LINKED ISSUE #852: Upgrade cider-nrepl version used by Calva
https://github.com/BetterThanTomorrow/calva/issues/427#issuecomment-734099774

https://github.com/clojure-emacs/cider-nrepl/blob/master/CHANGELOG.md

At the time of this writing Calva is using 0.23.0.

### LINKED ISSUE #896: Calva REPL lags when evaluation throws an error
When an evaluation in the Calva REPL throws an Exception it will take a couple of seconds (5 to 10 or so) to show the exception and return the prompt. E.g.

```
clj::user=> 
(/ 1 0)
```
Some seconds... 
```
; Execution error (ArithmeticException) at user/eval21385 (REPL:21).
; Divide by zero
```

Tested with jack-in Clojure CLI (empty deps.edn), leiningen and Clojure CLI started in the a terminal window + connect

Visual Studio Code:
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 wk ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

Calva:
Version: 2.0.138 and 2.0.134

### PR DESCRIPTION
**Pull request by PEZ**
## What has Changed?

We make the jack-in deps configurable and also bump them all to latest versions with the provided default settings.

Fixes #896
Closes #852 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *There is a CircleCI bug that makes the Artifacts hard to find. Please see [this issue](https://discuss.circleci.com/t/artifacts-tab-not-showing-unless-logged-in/32433) for workarounds.*
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [ ] Added to or updated docs in this branch, if appropriate

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and tested it there if so.
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse, @bpringe

### CODE REVIEW

**Comment by PEZ** [comment]
We should probably update the docs too.

**Comment by bpringe** [comment]
Closes #852

**Comment by bpringe** [comment]
I tested the VSIX as well.

**Comment by bpringe** [comment]
Great idea making these configurable!

**Comment by PEZ** [comment]
I think you can edit the PR description, @bpringe . That might auto-close the issue.

**Comment by PEZ** [comment]
Added the docs, @bpringe . This is good to go, me thinks, especially since you've tested it too. However, family calls here. If you find some time, please merge and release.

**Pull request merged**
