### PR TITLE
Fix REPL Window not accepting keys like cursor, return, etcetera

### LINKED ISSUE #516: REPL hangs after first eval
Regression:
Since *after* 2.0.66:

When running a CLI-tools based figwheel-main project, the REPL only evals the first form. Then it hangs on eval, but allows some editing of the line, as if [ENTER] is ignored.

To reproduce:
Simply get https://github.com/rpompen/mkproj-demo , or https://github.com/rpompen/mkproj if you want to generate the project yourself.

Then fire up the figwheel-main session.

Thanks in advance.

### PR DESCRIPTION
**Pull request by PEZ**
## What has Changed?

For some users, the REPL Window is often not accepting keyboard commands, like cursoring, return and such. In this PR I am enabling those commands on a few more Webview events to try see if that helps Calva know when the commands should be dispatched to the  REPL Window.

When this worked it should fix #516

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [ ] Created the issue I am fixing/addressing, if it was not present.
- [ ] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse, @bpringe

### CODE REVIEW

**Comment by cfehse** [comment]
@PEZ 

No this is not only on Linux. With version 2.0.69 on Window I experience the same behaviour.

**Comment by PEZ** [comment]
Thanks. I edited the description. I totally fail to reproduce it.

Is the VSIX from this PR behaving better?

**Comment by PEZ** [comment]
Got my first reports that the REPL window behaves better with this PR. I'll be merging this now. Then I can look at the problem tonight and see if I can be improved further. Tricky though, since I can't repro this..

**Comment by cfehse** [comment]
@PEZ 

I used the merged dev branch and that version works as "normal" as expected. In version 2.0.69 the REPL window was literally not usable on my systems.

**Comment by PEZ** [comment]
Thanks! Then I made the right call releasing this. Should reach the marketplace any minute now.

**Pull request merged**
