### PR TITLE
Handle the `unknown-op` status from test commands.

### PR DESCRIPTION
**Pull request by marcomorain**
Calva currently fails silently when the test commands fail due to the
unknown-op status. Here we handle that error and show a warning message
when it occurs. This doesn't address the root cause of the issue, but it
will help users to understand the problem.

This will help to debug #1269

Ping @pez, @bpringe

### CODE REVIEW

**Comment by marcomorain** [comment]
image

**Comment by marcomorain** [comment]
This PR needs work before it can be merged – when the test command fails the new REPL prompt is not printed (as seen in the screenshot)

**Comment by marcomorain** [comment]
Aha, the calls to `await session.test` will throw, which jumps over the call to `outputWindow.appendPrompt()`

**Comment by marcomorain** [comment]
@PEZ this should be good to review now.

**Comment by marcomorain** [comment]
image

I've moved the error message into the REPL output, rather than the VS Code warning pane.

**Comment by PEZ** [comment]
Thanks!

LGTM. Have you had a look, @bpringe?

**Comment by bpringe** [comment]
@marcomorain Thanks for this PR.

I installed the vsix and when I run this simple test using the `Run Current Test` command the repl seems to either freeze or stop printing things.

```clj
(ns test-lein.core-test
  (:require [clojure.test :as test]
            [test-lein.core :refer :all]))

(test/deftest a-test
  (test/testing "Some test"
    (test/is (= 1 1))))
```


I just get this message with nothing else:

```clj
; Running test: a-test…
```

Then I can't evaluate anything else, even if I run the command to interrupt evaluations. At least, I'm not seeing any results printed. Using the latest Calva version, this scenario works as expected.

**Comment by marcomorain** [comment]
@bpringe thanks for that – I was only testing the negative case when I was running this, and never tested actually running tests 🤦 

Is there a way to run a test like yours in CI?

**Comment by marcomorain** [comment]
This is ready for review again 🙏

**Comment by bpringe** [comment]
> Is there a way to run a test like yours in CI?

What do you mean, exactly?

I tested the VSIX and it seems good to me!

**Comment by marcomorain** [comment]
> What do you mean, exactly?

I mean, is there a way that we write an integration test of that starts Calva, connects to a REPL server, evaluates some source, and runs a test?

**Comment by bpringe** [comment]
@marcomorain Oh, it may be possible. I'm not sure how easy it would be to involve a repl in integration tests, though.

**Comment by PEZ** [comment]
It would be a super awesome addition to be able to run tests like those in CI! Please open an issue about it. And a PR is of course super duper welcome. We have an integration test setup that we run in CI. It only starts VS Code and checks that Calva loads. (Or some such). That's where we would hook this test in, most probably.

**Pull request merged**
