### PR TITLE
Reimplement the "Require REPL Utilities" command

### LINKED ISSUE #451: "Require REPL Utilities" command is broken
I was looking into #433 and I realized this command doesn't work, at least for me. I run the jack-in command, the repl window opens, and then I run the Require REPL Utilities command. I see `REPL utilities (like apropos, dir, doc, find-doc, pst, and source) are now available.` in the Calva says window, but I get an error when I try to use `doc`:

image

### PR DESCRIPTION
**Pull request by cfehse**
## What has Changed?

- Reimplemented the ""Require REPL Utilities" command
  1. Ensure that the namespace of the file exists in the REPL
  2. Evaluate the require form in the editor session
  3. If a REPL window for the editor filetype exists:
     a. Set the REPL window to the namespace of the file
     b.  Evaluate the require form in the REPL window session

Fixes #451

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [x] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [x] Made sure the PR is directed at the `dev` branch (unless reasons).
- [x] Read the source changes.
- [x] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [x] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse

### CODE REVIEW

**Comment by PEZ** [comment]
> If a REPL window for the editor filetype exists:
> a. Set the REPL window to the namespace of the file
> b. Evaluate the require form in the REPL window session

This shouldn't be necessary, right? Whatever is required in the namespace is shared. Or, are there any dynamic vars or something that gets set when loading the utilities?

**Comment by bpringe** [comment]
Thanks for making this change @cfehse!

> > If a REPL window for the editor filetype exists:
> > a. Set the REPL window to the namespace of the file
> > b. Evaluate the require form in the REPL window session
> 
> This shouldn't be necessary, right? Whatever is required in the namespace is shared. Or, are there any dynamic vars or something that gets set when loading the utilities?

Yeah I don't think that should be necessary either, because the editor and REPL window share a REPL session (or at least they should, from my understanding).

**Comment by cfehse** [comment]
@bpringe @PEZ 

> This shouldn't be necessary, right? Whatever is required in the namespace is shared. Or, are there any dynamic vars or something that gets set when loading the utilities?

Perhaps it shouldn't - and well sharing the same session: the REPL Window session is a clone of the editor session. Means this "sharing" the same session?

**Comment by PEZ** [comment]
No, they have different sessions alright. But if you `(def foo :foo)` in a namespace in your app, then it is ”attached” to that namespace, so any session will see it, because all sessions are for the same app. It would be pretty crazy otherwise, even if also pretty cool if each session had its own app.

What is *not* shared between sessions are dynamic variable bindings, like `*ns*`, `*1`, etcetera (and any dynamic variables you define yourself). At least not shared for Clojure sessions. ClojureScript sessions share everything, if I am correctly informed.

**Comment by cfehse** [comment]
@bpringe  @PEZ 

> This shouldn't be necessary, right? Whatever is required in the namespace is shared. Or, are there any dynamic vars or something that gets set when loading the utilities?

In fact this is *not* necessary.  I simplified the implementation which works for me in Brandon's test project but in a more real life project there seems to be a timing problem. It sometimes does not work the first time the command is executed.

**Comment by cfehse** [comment]
@bpringe @PEZ

And for some files, it doesn't work at all. *gg*

**Comment by bpringe** [comment]
>in a more real life project there seems to be a timing problem

I thought it might be a timing issue as well when I first started looking into it, because the results (when it worked and did not work) seemed to be very random, which could indicate some kind of race condition / timing issue.

**Comment by cfehse** [comment]
@bpringe  @PEZ 

Now this works for me in all circumstances:

1. Create the namespace if it does not exist.
2. Evaluate the form `(in-ns '<namespace)` (we do this in the "normal" evaluation commands as well).
2. Evaluate the form to require the tools.

Please take a look at the changes.

**Pull request merged**
