### PR TITLE
[WIP] Add drag swexp back up

### PR DESCRIPTION
**Pull request by PEZ**
This PR is about adding the drag up/down, previous/next Paredit commands, as suggested in #500

To be consistent with the corresponding movement and selection commands, I am naming the commands like so (name suggestions from the feature request in brackets):

- [x] Drag-backward-up (up)
- [x] Drag-forward-down (down)
- [x] Drag backward-down (previous)
- [x] Drag-forward-up (next)

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse, @bpringe

### CODE REVIEW

**Comment by PEZ** [comment]
@bdevel : I've started implementing the missing drag commands here. You can help me by testing and providing feedback as I progress. The CI pipeline will build a new VSIX package whenever I push to that branch. You'll find it under the **build** step in the checks above. (I think you need to be logged in at CircleCI to pick up the package.)

So far I have almost implemented the drag-back-up command. The lacking things there are: 

1. Removing whitespace if the dragged form is the first one in the list
1. A default keyboard shortcut
1. Add it to the documentation (I'll postpone this a bit until we have decided we have the right behaviour in place)

Also, I have decided to name all these commands **drag** instead of **push**. After having used the left/right command a while, it does feel a lot more like dragging, than pushing, since the cursor moves with the form. (I guess you already knew, but I had to experience it. 😄)

**Comment by bdevel** [comment]
Great, I'll take a look. I'll have to figure out how to get the build installed. Thanks.

**Comment by PEZ** [comment]
That's pretty straightforward: https://github.com/BetterThanTomorrow/calva/wiki/Testing-VSIX-Packages#installing-a-vsix-package

**Comment by PEZ** [comment]
Hmmm, OK, so quite bug ridden right now...

**Comment by bdevel** [comment]
I got the branch cloned, built, and installed. It was actually pretty easy, great docs!

I tried several scenarios and it works well. Only quirk I saw was that the command will not run if a form is selected. You must exit the selection. This is different behavior than drag left/right which will perform the command and exit the selection. Not a deal breaker but may be an easy fix. 

Looking forward to drag down!

**Comment by PEZ** [comment]
Ah, great that you did it that way. The more people that can build and hack on Calva, the better. 😄 

I actually did that on purpose with the selection. Didn't think about that I had made another decision for left/right. I'll fix.

**Comment by PEZ** [comment]
Now I have added a default keyboard shortcut binding. Also refactored the command code some to hopefully gain some accuracy and speed when adding drag-down. 😄 

I wish I could figure out how to factor the unit tests better, because it gets an awful lot of boilerplate as it is now. I have this idea that my mini-language for documenting the tests should be possible to use to generate the tests as well. But how that would be done still eludes me.

**Comment by PEZ** [comment]
Hello again. I'm back at this, from a day-job related pause.

First version of drag down added. It doesn't yet handle the newline scenarios fully. I will need to think a bit of both what should happen, and how to do it. On the what should happen account, I think it makes sense that drag forward and then backward should leave things like thet were before any dragging happened.

**Pull request merged**
