### PR TITLE
Add Gradle project type for jack-in

### LINKED ISSUE #614: Support/detect clojurephant for Jack-in
Hello,

I'm using VS-Code and gradle with clojurephant to develop clojure. It would be great if we could have detection / support for that in calva.

https://clojurephant.dev/clojurephant/ . I don't know how that works with calva but if you point me in the right direction I can document that in one of the issues: 

https://github.com/clojurephant/clojurephant/issues/47

### PR DESCRIPTION
**Pull request by ajoberstar**
Added a new project type and default connect sequence for Gradle+Clojurephant and clj-only REPLs.

## What has changed?

- Add jack-in support for Gradle / [Clojurephant](https://github.com/clojurephant/clojurephant) projects
- Since Gradle supports two different DSL's (Groovy and Kotlin) with different extensions, the existing single `useWhenExists` marker file support had to be extended to support multiple files. It seems like the impact is contained to just that one file, so it seems pretty safe.
  - While it might seem to make more sense to use `build.gradle` and `build.gradle.kts` instead of the settings files, a `build.gradle` can be a subproject instead of the root. The `gradlew` wrapper command used to kick off gradle will be a sibling to the `settings.gradle` in the root, where multiple build.gradles could be nested deeper in a multi-project build. 
  - I omitted including any CLJS types by default, as Gradle's classpath conventions don't mesh well with the out-of-box CLJS REPLs. Still working on how to best support them in Clojurephant and can send a new PR when those features are settled.

Fixes #614

## My Calva PR Checklist

If this PR involves only documentation changes, I have:

- [x] Read [Editing Documentation](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva#editing-documentation)
- [ ] ~Directed this pull request at the `published` branch.~
- [x] Built the site locally (if the changes were more involved than simple typo fixes), and verified that the site is presented as expected.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_ (if there was is an issue for the documentation change)
  - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
  - [ ] ~If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.~

If this PR involves code changes, I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [ ] Tests
  - [ ] Tested the particular change
  - [ ] Figured if the change might have some side effects and tested those as well.
  - [x] Smoke tested the extension as such.
  - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
  - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
  - [ ] ~If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.~
- [ ] ~Created the issue I am fixing/addressing, if it was not present.~
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Comment by ajoberstar** [comment]
- I've done some basic testing on Linux, plan to also do Windows (don't have access to a Mac).
  - **EDIT** Windows testing didn't work, so will need to make some tweaks
  - **DOUBLE EDIT** Woops used Calva connect instead of Calva jack-in. It seems to be working just fine
- Unsure where the unit tests for this functionality are, couldn't find existing ones for these files, so open to your preference there
- Probably want to introduce a configuration option to control the task kicked off (currently using `clojureRepl`).

**Comment by bpringe** [comment]
Thanks for this!

> Unsure where the unit tests for this functionality are

I don't think there are any, unfortunately.

**Comment by bpringe** [comment]
I'd like to leave this to @PEZ to review when he gets back from vacation. The changes seem pretty isolated, though, so it seems pretty safe.

**Comment by PEZ** [comment]
Thanks, @ajoberstar! I'm impressed that you found your way in this quite messy part of Calva. 

Your changes look solid and to the point. I like to test things before merging, but have no project to test the actual addition. Can you add a sample project to `test-data/projects`, maybe?

**Comment by ajoberstar** [comment]
> Thanks, @ajoberstar! I'm impressed that you found your way in this quite messy part of Calva.
> 
> Your changes look solid and to the point. I like to test things before merging, but have no project to test the actual addition. Can you add a sample project to `test-data/projects`, maybe?

@PEZ Sure thing! Test project added. Let me know if there's anything else.

**Comment by PEZ** [comment]
Sorry for slow response, @ajoberstar! And thanks for the test project.

When I try this from the `test-data` directory, I am not being presented the gradle test project:

image

I should, shouldn't I?

Also, when opening the gradle test project in a VS Code window of its own, Calva jack-in and similar commands does not activate, neither does clojure-lsp start.

Is there some init of the gradle project I need to do to make it create the necessary files?

**Comment by ajoberstar** [comment]
If your VS Code window is open to the `test-data/my-gradle` directory it does work for me (using the Extension Development host and VSIX). However, if I open the `test-data` folder like you did, I also don't see it in the list of Clojure project roots. 

There must be another code path I didn't find for project root detection. I'll look for that and push up additional changes.

**Comment by ajoberstar** [comment]
Well that was easy, just needed to add it to the list of project file names. Let me know if you run into further trouble.

**Comment by PEZ** [comment]
Oh, missed that you had updated here. I'll test again and get back to you.

**Review by PEZ — APPROVED** [review]
Looks great. Works great. Thanks for your work, @ajoberstar!

**Pull request merged**
