### PR TITLE
handle nrepl input request with error msg

### LINKED ISSUE #377: clojure.core/read-line doesn't work in Calva REPL
Repro
1.  `lein new app shopping-list`

2.  Add the following code to "src/shopping_list/core.clj"

         (defn prompt
          "get information from the user"
          [msg]
          (println msg)
          (read-line))

  3.  Jack-in to the project and load the file above `ctrl+alt+c enter`
  4.  Evaluate `(prompt "What is my name")` in the Calva REPL

  Calva REPL becomes unresponsive

  5.  In a new terminal window connect to running nREPL server. `lein repl :connect`
  6.   Evaluate `(prompt "What is my name")` in the terminal. 

All is well. Input is entered at the REPL successfully

### PR DESCRIPTION
**Pull request by jmingtan**
## What has Changed?

- when nrepl returns a request for user-input, print a error msg to the user and set nrepl's stdin to an empty line
- more work is needed to support handling user-input, will look into it and hopefully submit another PR?
- in the meantime, this patch will stop Calva's REPL window from hanging

Fixes #377 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [ ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [ ] Created the issue I am fixing/addressing, if it was not present.
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

## The Calva TEAM PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse

### CODE REVIEW

**Comment by PEZ** [comment]
Thanks! I'll have a look.

> more work is needed to support handling user-input, will look into it and hopefully submit another PR?

Please do!

**Comment by PEZ** [comment]
Super awesome. I hope you go ahead with prompting for the input!

**Comment by cfehse** [comment]
@jmingtan @PEZ 

I am currently working on the NReplEvaluation class in `nrepl/index.ts` to centralize all the processing there. Perhaps we can synchronize our work on the input provider a bit.

**Comment by jmingtan** [comment]
@cfehse sure, I'll take a look at your PR before doing anything 👍 

Thanks to the team for all your work on Calva!

**Pull request merged**
