### PR TITLE
Fix some parsing issues

### LINKED ISSUE #802: Various parsing issues
As discussed in #calva, we'll use this issue to collect some parsing issues that are discovered for the time being.

---

### Handling of number before discard / ignore marker

In `clj` I get the following results:
```
user=> [1#_2]
[1]
user=> [1#_ 2]
[1]
user=> [+1#_2]
[1]
```
So it appears that in each case, `1` (or `+1`) is being recognized as a number, and then starting from `#_`, there is a discard expression that extends to include the `2`.

I tried a similar sequence for Calva's clojure-lexer and found:
```
npx ts-node
> import { Scanner } from './clojure-lexer'
{}
> let s = new Scanner(32768)
undefined
> s.processLine("[1#_2]")
[
  { type: 'open', offset: 0, raw: '[', state: { inString: false } },
  { type: 'id', offset: 1, raw: '1#_2', state: { inString: false } },
  { type: 'close', offset: 5, raw: ']', state: { inString: false } },
  { type: 'eol', raw: '\n', offset: 6, state: { inString: false } }
]
> s.processLine("[1#_ 2]")
[
  { type: 'open', offset: 0, raw: '[', state: { inString: false } },
  { type: 'id', offset: 1, raw: '1#_', state: { inString: false } },
  { type: 'ws', offset: 4, raw: ' ', state: { inString: false } },
  { type: 'lit', offset: 5, raw: '2', state: { inString: false } },
  { type: 'close', offset: 6, raw: ']', state: { inString: false } },
  { type: 'eol', raw: '\n', offset: 7, state: { inString: false } }
]
> s.processLine("[+1#_2]")
[
  { type: 'open', offset: 0, raw: '[', state: { inString: false } },
  { type: 'id', offset: 1, raw: '+1#_2', state: { inString: false } },
  { type: 'close', offset: 6, raw: ']', state: { inString: false } },
  { type: 'eol', raw: '\n', offset: 7, state: { inString: false } }
]
```
It looks like in these cases `#_` is being seen as part of what comes immediately before.

Note that:
```
> s.processLine("[:a#_1]")
[
  { type: 'open', offset: 0, raw: '[', state: { inString: false } },
  { type: 'kw', offset: 1, raw: ':a#_1', state: { inString: false } },
  { type: 'close', offset: 6, raw: ']', state: { inString: false } },
  { type: 'eol', raw: '\n', offset: 7, state: { inString: false } }
]
```
seems correct, as in `clj`, one gets:
```
user=> [:a#_1]
[:a#_1]
user=> (type :a#_1)
clojure.lang.Keyword
```
So far I think for numbers and delimiters of collections, one doesn't need to put a space before `#_` for there to be appropriate recognition of a following discard expression.

However, for characters, symbols, keywords, and symbolic values (e.g. `##NaN`), not having a space makes a difference in what ends up being recognized.

It may be obvious, but this analysis may not be complete.

### PR DESCRIPTION
**Pull request by PEZ**
## What has Changed?

From #802 we learnt that Calva's Clojure lexer fails on some areas. This PR tries to fix them

* [x] `1#_foo` => `lit: 1`, `ignore: #_`, `id: foo`
    * [x] This is really about not allowing integers to start symbols/ids
* [x] `_foo` => `id: _foo` (and `_` => `id: _`)
* [x] Various hex syntax fixes
    * [x] Introduce `invalid` tokens for things like `0xg`
* [x] Various octal syntax fixes
    * [x] Introduce `invalid` tokens for things like `08`
* [x] `1N` => `lit: 1N` (BigInt)
* [x] `1M` => `lit: 1M` (BigDecimal, other examples: `00M`, `+18998.18998e+18998M`, and `-61E-19471M`)
* [x] `+3r11` => `lit: +3r11`
* [x] `1/2` => `lit: 1/2` (ratios)
* [x]  character literals => lit
* [x]  symbolic values => lit
* [x] terminate named literals
* [x] lots of whitespace characters

This work also got me to see that these where broken:

* [x] `4.2` => `lit: 4.2` (”floats” in general)
* [x] Generated test data produced symbols containing `^` (as mentioned in #746)

As for the `invalid` tokens, this behaviour has been added to the `tmLanguage` syntax highlight grammar as well, to give a consistent/predictable behaviour (WYSIWYG, if you like).

- Fixes #802
- Addressing #746

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *There is a CircleCI bug that makes the Artifacts hard to find. Please see [this issue](https://discuss.circleci.com/t/artifacts-tab-not-showing-unless-logged-in/32433) for workarounds.*
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and tested it there if so.
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse, @bpringe

### CODE REVIEW

**Comment by PEZ** [comment]
There we go. I think this should take care of all parsing issues found and reported by @sogaiu in #802. It's been a long day, though, and I am pretty wasted right now, so I might be missing a lot of nuance. Please help in QA here, Calva-friends.

**Comment by sogaiu** [comment]
Hope you have (or are getting) adequate rest :)

I'm going over f8e3c55.

For character literals, the form feed character seems to work better -- I'm now getting a `lit`:)

For the newline character, I'm still getting:
```
> s.processLine("\\\n")
[
  { type: 'junk', offset: 0, raw: '\\', state: { inString: false } },
  { type: 'ws', offset: 1, raw: '\n', state: { inString: false } },
  { type: 'eol', raw: '\n', offset: 2, state: { inString: false } }
]
```

Will report back with further results when I have them, but FWIW, everything preceding the newline character case seemed to be working better :+1:

**Comment by PEZ** [comment]
Thanks for testing this out! I forgot to add a test for quoted newline and other control characters.

Here's the changes for this quoted characters, btw: https://github.com/BetterThanTomorrow/calva/pull/838/commits/180d85f0136fe3db9c5910b9472677bc8caeef63

**Comment by PEZ** [comment]
Fixed the quoted `\n` bug. Also `\r`. `.` doesn't match those, duh...

**Comment by sogaiu** [comment]
I'll do some more checking in a bit.

Wanted to mention that I noticed an additional thing.  Should I put that in the original issue?  Open a new one?

FWIW, it is related to what is considered whitespace.  Here is a summary of what I've found about it for reference: https://github.com/sogaiu/tree-sitter-clojure/blob/master/grammar.js#L6-L32

**Comment by sogaiu** [comment]
Sorry, I missed the following earlier.

With fa9200d I get:
```
> s.processLine("[+1#_2]")
[
  { type: 'open', offset: 0, raw: '[', state: { inString: false } },
  { type: 'id', offset: 1, raw: '+1#_2', state: { inString: false } },
  { type: 'close', offset: 6, raw: ']', state: { inString: false } },
  { type: 'eol', raw: '\n', offset: 7, state: { inString: false } }
]
> s.processLine("[-1#_2]")
[
  { type: 'open', offset: 0, raw: '[', state: { inString: false } },
  { type: 'id', offset: 1, raw: '-1#_2', state: { inString: false } },
  { type: 'close', offset: 6, raw: ']', state: { inString: false } },
  { type: 'eol', raw: '\n', offset: 7, state: { inString: false } }
]
```
In `clj`:
```
user=> [+1#_2]
[1]
user=> [-1#_2]
[-1]
```

**Comment by PEZ** [comment]
> Wanted to mention that I noticed an additional thing. Should I put that in the original issue? Open a new one?

For now, add it to the issue. I'm super happy you asked, because it's really not clear cut. Right now though, I have my brain tuned on the parser and can as well look at some more issues with it. That said, I don't quite follow what it is about from the link you provided, so it might be something tricky about it that makes me want it in a separate issue anyway. We'll see. 😄

**Comment by PEZ** [comment]
> +1#_2

Hmmm, I do hope this will not prove too hard. At the surface of it I think it might be quite tricky..Maybe I am closing in to a point where I need a different take on those prefix chars...

**Comment by sogaiu** [comment]
Thanks for the guidance.  I added a comment here: https://github.com/BetterThanTomorrow/calva/issues/802#issuecomment-720363343

(I'm sorry I don't understand the lexer enough to be of much help in fixing things.  Hopefully as I test more I will understand it better.)

**Comment by PEZ** [comment]
You are helping a lot by having this lexer as one of your test implementations and by preparing such excellent reports!

The lexer is really super simple, btw. It basically just tests a bunch of regexes in order and pick whichever match is the longest or first. Then there is a catch-all `junk` regex at the end that matches one character of anything, to keep the lexer move along even when none of the recognised token types have matched. The actual token types produced are what makes sense and also what the structural editor needs.

**Comment by PEZ** [comment]
In theory it could all be done using a DFA, which would speed things up dramatically. But since it is already quite speedy, I will probably never get to where I choose to spend the huge chunk of work and thinking involved. 😄

**Comment by PEZ** [comment]
> +1#_2

Fixed it! 🎉

**Comment by sogaiu** [comment]
Thanks for the explanation of the lexer.  I had a quick look at `clojure-lexer.ts` and `lexer.ts` and I think I was able to match your description to some of the code (e.g. scan()).

Also, I verified that 6cf0c67 works with `+1#_2` and `-1#_2` :+1:

**Comment by PEZ** [comment]
Whitespace should now be fixed to match what Clojure uses.

**Comment by sogaiu** [comment]
I verified that cd2ffed recognizes the individual characters mentioned in https://github.com/BetterThanTomorrow/calva/issues/802#issuecomment-720363343 as `ws` :+1: 

I didn't quite understand what cd2ffed was doing, but here is some session info:
```
user=> \c#_
Syntax error reading source at (REPL:2:0).
Unsupported character: \c#_
user=> \c
\c
```
I'm not sure what's going on with Clojure for the first bit here.

FWIW, what I got from Calva's lexer was:
```
> s.processLine("\\c#_")
[
  { type: 'lit', offset: 0, raw: '\\c#_', state: { inString: false } },
  { type: 'eol', raw: '\n', offset: 4, state: { inString: false } }
]
```
I presume this was your intent.

On a separate note, another case popped up, so I will add that to the issue.

**Comment by PEZ** [comment]
Yes, I made the same tests with **clj** and realised I had gone a bit overboard with matching that ignore marker wherever it showed up. 😄 

That new case is fixed. I suspect there are a lot of similar cases.

**Comment by sogaiu** [comment]
I tried running some tests with 943a4b1 but have yet to encounter any problems :+1: 

For Calva testing, so far I have implemented some form of testing for the following sorts of things along with various "separators":

* comment
* nil
* boolean
* character
* keyword
* number
* string
* symbol
* symbolic value
* list
* map
* vector
* set

I have generators for other constructs (e.g. reader conditionals, anonymous functions, etc.), but currently I lack the code to verify these for Calva.  I hope to get around to covering the rest at some point.

Just wanted to let you know what kinds of things have and have not been tested for from this end :)

**Comment by sogaiu** [comment]
I discovered that I had a fair number of the tests disabled, so I will go back and see what happens as I re-enable them.

My apologies :sweat_smile:

**Comment by sogaiu** [comment]
Having re-enabled, so far I've only encountered one thing: https://github.com/BetterThanTomorrow/calva/issues/802#issuecomment-721013544

I also added some preliminary support for:

* regex
* reader conditional
* reader conditional splicing
* anonymous functions

These didn't turn up anything new :)

**Comment by PEZ** [comment]
Fixed the N-numeric literal split. Also simplified away the various invalid number cases for now.

**Comment by sogaiu** [comment]
The generative testing hasn't found problems with 6832a9f so far :+1: 

I also manually checked that `0X0N` and `08.01` are recognized correctly.

Perhaps you are aware, but just noting here that:
```
user=> 008
Syntax error reading source at (REPL:2:0).
Invalid number: 008
```
Calva appears to be generous in accepting this.

**Comment by PEZ** [comment]
Apropos `008`. The Clojure reader also sort of accepts it at the lexing level, right? So it sees it as a number, but figures it as being an invalid such. So I think it makes sense that Calva lexes it as a token of type `lit`. A commit ago it sexed it as `invalid`, but I decided to backtrack on that for now.

**Comment by sogaiu** [comment]
That makes sense, thanks for the explanation :)

**Pull request merged**
