### PR TITLE
Add a hover to results annotation w/ full results

### LINKED ISSUE #104: Compiler error message doesn't line wrap
Even when I've set Code to wrap lines, the error message from the compiler doesn't wrap:
screenshot 2019-01-26 at 21 11 51

### PR DESCRIPTION
**Pull request by PEZ**
This pull request:

Fixes #104, and addresses #79.

Introduces the following change(s):
- Inline result annotation now have a hover showing the full results.
- The hover has a `Copy` link, that copies the results to the clipboard.
- The inline displayed result takes up less width.

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Referenced the issue I am fixing/addressing.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Updated the `[Unrleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

Ping: @kstehn

### CODE REVIEW

**Comment by PEZ** [comment]
Looks like so:

image

**Comment by kstehn** [comment]
Just tested this and works good.
I guess compiling error will get better when the PR #330 gets merged.

From my side it is good to go.

**Comment by PEZ** [comment]
Compiling error?

**Comment by PEZ** [comment]
Ah, I see. Yeah, we should merge that as well, and Marc can file a new issue if it doesn't fix his use case.

**Comment by kstehn** [comment]
Something like this 
image

**Comment by Yunfeng-Song** [comment]
i think this feature is now gone due to the implement of output-repl thing. Now if I hove over, it just displays a button Open results window. I really like this feature. is it a bug or this feature is gone forever?

**Pull request merged**
