### PR TITLE
add special nrepl middleware flag

### LINKED ISSUE #2133: Notebook nrepl integration flag
Calva notebooks currently send a normal `eval` message to nrepl when running a cell.
Setting a special flag would make it possible for integrations like Portal to have special handling for them in the middleware.
Set the `'nrepl.middleware.eval/env': { 'calva-notebook': true, notebook: true }` for all notebook evals.

### PR DESCRIPTION
**Pull request by Cyrik**
## What has changed?

- Added two new experimental nrepl eval message option flags to notebook evaluation
  - These are meant to make portal integration more robust, but can be used by other middleware as well
  - `eval` middleware can check for these options and do more or return different results based on the fact that the code is running in a notebook

Fixes #2133

## My Calva PR Checklist

I have:

- [X] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [X] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [X] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [X] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [X] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
~- [ ] Added to or updated docs in this branch, if appropriate~
~- [ ] Tests~
  ~- [ ] Tested the particular change~
  ~- [ ] Figured if the change might have some side effects and tested those as well.~
- [ ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
  - [X] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
  ~- [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.~
- [X] Created the issue I am fixing/addressing, if it was not present.
- [X] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [X] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Comment by bpringe** [comment]
Looks good to me. Is this all this PR will be adding? @PEZ Do we want an issue and changelog item for this?

**Comment by Cyrik** [comment]
Yeah, that's all this will add. Wasn't sure if we need any extras for now since it's still kind of experimental specifically for portal. 
Once we've had some time to see if it's enough for portal it'd make sense to put it into the docs so that other integrations can take advantage of it.

**Review by PEZ — COMMENTED** [review]
LGTM!

**Comment by PEZ** [comment]
And, yes, even if tiny change, we want an issue and a changelog item. This is for three reasons:

1. The Changelog is a great tool when users run into problems.
2. It is a good way to track what problem a change solves.
3. It brings visibility to features in Calva. (”Calva has Notebook support? Cool!”)

**2** there, means that the issue should have the problem statement.

**Pull request merged**
