### PR TITLE
Make REPL History work in a cleared window

### LINKED ISSUE #2545: REPL History commands do not work in a cleared window
If I select all text in the `output.calva-repl` window and delete everything, "Calva: Show next REPL History Entry" and "Calva: Show previous REPL History Entry" commands will fail with "Expected to find text at the prompt!" message. Apparently they cannot find the prompt and fail because of that. I think it that situation it should just accept the whole text as the last input.

### PR DESCRIPTION
**Pull request by mrkam2**
## What has changed?

If I select all text in the `output.calva-repl` window and delete everything, "Calva: Show next REPL History Entry" and "Calva: Show previous REPL History Entry" commands will fail with "Expected to find text at the prompt!" message. This fixes the issue by assuming that if no prompt is found in the window, all of its content is after the last prompt.

Fixes #2545.

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

### CODE REVIEW

**Review by PEZ — CHANGES_REQUESTED** [review]
Thanks! 🙏 

There's a unit-test checking that we return undefined in this situation. I don't know if that may mean some other behaviour relies on it. The solution may be to just fix the test, but I'm not familiar enough with this to say for sure. It was @bpringe implementing the REPL History iirc. 

* https://app.circleci.com/pipelines/github/BetterThanTomorrow/calva/7898/workflows/0ab627b4-5a63-4dc0-9974-bcd79565fd01/jobs/42470

Also, again you deleted the checklist. So you'll need to re-install it and check items off as they are completed.

**Comment by PEZ** [comment]
Thanks! 🙏 

I have tested it, and it works as advertised. Will give @bpringe some more time to chime in, then we'll merge.

**Review by PEZ — APPROVED** [review]
LGTM. WDYS, @bpringe ?

**Comment by mrkam2** [comment]
I tested it and it works quite well. It is also not used in any of the other code besides the REPL History Show Next/Show previous.

One thing to note is that if I enter some text and then use the command, the prompt is printed next to it:

`foo` -> `fooclj꞉user꞉>`.

Nevertheless, the `foo` text is remembered as the last entered command and further iteration over history works well.

I'm coming up with a fix to this issue as well. So don't merge yet.

**Comment by PEZ** [comment]
I'll let you sort the conflict in the Changelog out, @mrkam2. It's only that something has been released since you updated your branch. git is surprisingly bad at figuring out what to do with these conflicts. 😄

**Comment by PEZ** [comment]
> I'm coming up with a fix to this issue as well. So don't merge yet.

Roger.

**Comment by mrkam2** [comment]
> > I'm coming up with a fix to this issue as well. So don't merge yet.
> 
> Roger.

So I updated the PR so that it doesn't insert a prompt when there is none and that it doesn't add any unnecessary newline characters (after prompt removal it was inserting a blank line above the history entry).

> I'll let you sort the conflict in the Changelog out, @mrkam2.

I resolved it.

**Review by PEZ — COMMENTED** [review]
Looks great. Works great.

**Comment by bpringe** [comment]
I think changing that test is fine. I don't know that the new behavior won't cause something undesirable, but I think it's fine to go with the changes and see what happens

**Pull request merged**
