### PR TITLE
Fixing #506 select back/fwd stack issue w/ selection can't grow

### PR DESCRIPTION
**Pull request by PEZ**
WIP: I am fixing the issue and also adding some  unit tests for the Paredit grow and shrink selection stack.

Eventually #506 should be fixed. 😄 

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse, @bpringe

### CODE REVIEW

**Comment by PEZ** [comment]
I got so confused by the names `rangeToSelectionStart/End`, so I renamed them ti `Left/Right` instead, because that is what we care about when growing the selection backward and forward. That name change made me see that their implementation were wrong as well, so that they worked in the editor was a bit of a coincidence.

Right now some things that used to work, doesn't work any longer, and we have new inconsistencies between editor and REPL window. I think the way to go is to continue to challenge the naming and thus the implementations in order to try remove some of the confusion and all of the inconsistencies between the two implementations.

@bpringe : It seems the bug I am trying to fix here has a lot of the causes in common with the bug you are fixing in #508. In this PR I have a bit of better coverage with Unit tests, and the naming change is really necessary. I suggest that if you get time to work on things before I do, that you base your fix off of this branch. Let's keep syncing!

**Comment by bpringe** [comment]
@PEZ I agree that the naming change for consistency is much needed! This is what I was getting at in my PR, and the confusion I was referring to. It's well worth the effort and refactoring.

**Comment by PEZ** [comment]
It's a bit funny, because I just had this flow and added lots of stuff and everything just worked. So I thought everything was dandy, but now it is obvious that there is some serious cleaning up needed. 😄 

I'm starting to think that we could get to a less confusing state by removing the `selectionStart/End` properties entirely and go via `selection` all the time. I'm not sure, because `selection` is just something I added a few days ago, but it seems it is less confusing than dealing with the mix of start/end, forward/backward, left/right, anchor/active...

**Comment by bpringe** [comment]
Yeah I noticed some seemingly redundant properties like that, but didn't have the time to investigate much. I was thinking the same, going off of selection alone and removing the start/end ones would probably be a good idea.

**Comment by bpringe** [comment]
I was just thinking... currently I think the selection is sort of represented in three places in the EditableDocument:
- selectionStart and selectionEnd
- selection
- growSelectionStack (which I think could be just called selectionStack)

Maybe we can have the selectionStack be the source of truth, and the selection is derived from it.

Furthermore we may be able to do away with the anchor and active concept and move to purely two-item arrays for selections, where (first selection) is always greater than (second selection) (to put it in clojure terms 😄). Let me demonstrate the idea briefly, if I can.

Here is an example selectionStack:

```clojure
[[1 2]
 [3 5]]
```
First the user selected from 1 to 2, then from 3 to 5. The selection is derived from the selection stack using a function like getSelection(), which returns `[(min (flatten selectionStack)) (max (flatten selectionStack))]`

The only place we need to be concerned about direction is when moving the cursor inside the forward/backward commands.

This would surely require rewriting some code, but I think a simplified model could simplify the code more, and be worth it in the long run.

**Comment by bpringe** [comment]
There may be some holes in that model like possibly when selecting one way by one increment, then not undoing, but deselecting the other way by a different increment than the previous selection. This could possibly be solved though by not restricting the array numbers to the first one being less than the second. And instead they could sort of indicate direction implicitly like I think happens now in some places (IIRC).

So like a selectionStack of:

```clojure
[[1 2]
 [3 5]
 [5 4]]
```
Means the user selected, in two actions, forward from 1 to 5, then in another action, deselected from 5 backward to 4. In this model the current selection would be calculated as 

```clojure
[(first (first selectionStack) (last (last selectionStack))]
```

Which yields `[1 4]`. And then if needed, that could be sorted ^. This actually might be more intuitive.

**Comment by PEZ** [comment]
Sounds good. Would be possible also to just have `{anchor: x, active: y}` objects on the stack, like we have today, right? It's similar to the semantics that the VS Code editor uses, which is why I introduced it.

**Comment by PEZ** [comment]
Slowly inching my way there, @bpringe . I think my current unit testing tactics won't scale. But they have helped me fix so that paredit  for editor and repl window are bug compatible and to get lateral sexpr selections to work.

## Notes:

I think we could patch it so that all forward/backward selections work... but I also think it is better to take some more steps towards the selection stack being the single source of selection truth like you have thought up there.

One of my fixes involved using the vscode Selection `anchor` and `active` instead of it's `start` and `end` when mapping to EditableDocument selections. So that's one source of this whole confusing. VS Code Selections has both anchor/active and start/end, of which the latter maps to what I have starting to name left/end. Our replreadline document's start/end corresponds to the anchor/active of vscode Selections... gah. I am going to try get it such that we use these names:

* `anchor`, the start of a selection, can be left or right of, or the same as the end of the selection (active)
* `active`, the end of a selection, where the caret is, can be left or right of, or the same as the start of the selection (anchor)
* `left`, the smallest of `anchor` and `active`
* `right`, the largest of `anchor` and `active` 
* `backward`, movement towards the left
* `forward`, movement towards the right
* `up`, movement out of lists
* `down`, movement into lists

This will be in line with vscode when it comes to anchor/active, but introduce our own terminology  for the span of the selection. It will also keep the tradition of paredit with backward/forward and up/down.

If we succeed in getting it there, we can choose to then use start/end instead of left/right, but doing that now will cause chaos, because those currently mean something else in the REPL Window document...

**Comment by bpringe** [comment]
Ah yes, this makes sense if VS Code semantics are anchor and active. And also keeping things the same as paredit convention is a good idea (forward/backward), those were the details I was lacking. But yes, I think we could still simplify the code in the future, and maybe as a first step you could add the above bullet points to the code somewhere in a comment, or to a readme somewhere, so that people working on that part of the code will see it.

**Comment by PEZ** [comment]
I have implemented almost all of the changes now, except that the selection stack isn't yet the only source of truth. That will take some figuring, because today the actual selection in the editor is the source of truth for what is currently selected... We need to mirror that in a reliable way.

I have pasted the naming info as a comment in the code, and it is hopefully telling how things are named now, and not just how we want them to be named. 😄 

In the process I changed things to use more type checks than before.

I think it improves on what is currently released quite a bit so it might be time to merge. If you have some time, @bpringe, have a look and see if you agree.

**Comment by PEZ** [comment]
And now I also pushed the right/left naming changes...

**Comment by bpringe** [comment]
I like this a lot. I think it adds a lot of clarity, both the naming and the comments. I'm always taken aback by object orientated code though, i.e. the ModelEditSelection being a class with constructor, gets, and sets. But maybe it adds a little clarity in some places where used since it must be instantiated as `new ModelEditSelection`. 

Besides the tiny of bit logic for defaulting the anchor to active, I'm not sure if it provides much value. In most places I see it being passed an anchor, and where it's not, it might actually be beneficial to pass one for clarity at the site of the call. And if you were to make `anchor` required in the constructor, it makes the class basically pointless. Put another way, leaving it as it was and requiring it to be created as `{:anchor 1, :active 2}`, might be actually more explicit, clear, and simple. 

What I'm saying may be totally incorrect though! There may me more of a reason to use that class than I'm realizing.

**Comment by PEZ** [comment]
Yes, maybe it retracts clarity rather than add it, which was my intention. I was going to encapsulate the selection stack inside there, was my plan, and I also thought it was good to be explicit about when the selection had the same anchor as active position. The latter could be more clearly expressed though, I ran into problems not being able to figure out how to have two constructors and took the easy way out... Let's remember that we have a little mess here to clean up.

**Comment by PEZ** [comment]
I got fed up with not understanding what the paredit tests actually tested so I invented a small language for it, which is more precise and that I can understand quickly. Now the test tactics feel a bit more scalable to me, even. Please have a look, @bpringe , @kstehn , @cfehse .

**Comment by kstehn** [comment]
That is a cool idea, but when you would describe it as a grammar you would see there is a small problem.
The symbol `|` has two meaning one it could be the position or it could be the range-boundray.
But when they are always exclusive then i think its fine :)

**Comment by PEZ** [comment]
Good catch. I realised it is not exclusive, so changed the language some. Also distinguishing between ”empty” selection positions and ”empty" range positions.

**Comment by PEZ** [comment]
The test results, running `npm run unit-test`, look like so:

```
  paredit
    movement
      rangeToSexprForward
        ✓ ><(def foo [vec]) => |(def foo [vec])|
        ✓ (><def foo [vec]) => (|def| foo [vec])
        ✓ (d><ef foo [vec]) => (d|ef| foo [vec])
        ✓ (def foo [:foo :bar :ba><z]) => (def foo [:foo :bar :ba|z|])
        ✓ (def>< foo [vec]) => (def| foo| [vec])
        ✓ (def foo ><[vec]) => (def foo |[vec]|)
        ✓ (def foo [:foo :bar :><baz]) => (def foo [:foo :bar |:baz|])
        ✓ (def foo [:foo :bar :baz><]) => (def foo [:foo :bar :baz|])
        ✓ (>def> foo [vec]) => (def| foo| [vec])
        ✓ (>def foo> [vec]) => (def foo| [vec]|)
        ✓ (<def foo< [vec]) => (def foo| [vec]|)
      rangeToSexprBackward
        ✓ (def <foo [vec]<) => (|def| foo [vec])
      moveToRangeRight
        ✓ (|def >|foo>| [vec]) => (def foo>< [vec])
        ✓ (|def <|foo<| [vec]) => (def foo>< [vec])
        ✓ (<def< foo >|[vec]>|) => (def foo [vec]><)
      moveToRangeLeft
        ✓ (def >|foo>| ><[vec]) => (def ><foo [vec])
        ✓ (def <|foo<| ><[vec]) => (def ><foo [vec])
        ✓ (<|def<| foo >[vec]>) => (><def foo [vec])
    selection
      selectRangeFromSelectionRight
        ✓ (def foo [:foo >|:bar>| <:baz<]) => (def foo [:foo <:bar :baz<])
      selectRangeFromSelectionLeft
        ✓ (def foo [:foo >:bar> >|:baz>|]) => (def foo [:foo >:bar :baz>])
    selection stack
      ✓ should make grow selection the topmost element on the stack
      ✓ get us back to where we started if we just grow, then shrink
      ✓ should not add selections identical to the topmost
      ✓ should have A topmost after adding A, then B, then shrinking

  string
    keywordize
      ✓ keywordizes non-keywords
      ✓ leaves keywords alone
    unKeywordize
      ✓ un-keywordizes keywords
      ✓ leaves non-keywords alone
```

**Pull request merged**
