### PR TITLE
PROPOSAL enhance REPLwindow handling

### PR DESCRIPTION
**Pull request by cfehse**
## What has Changed?
- `src/connector.ts`
  - Moved code to create/show the REPL windows into a seperate function.
  - Improved error checking during the connect sequence.
-  `NReplEvaluation` in `nrepl/index.ts`
   - Enhanced the class to contain all message parsing.
   - Added properties which contain all information about the evaluation on resolve/reject.
   - Store any normal and error output of the evaluation for later use. 
   - Retrieve the stacktrace of an exception before reject the promise.
- functions `eval()` and `loadfile()` in `nrepl/index.ts`
   - Delegate message parsing and resolve/reject to the `NReplEvaluation`  class to ensure both methods behave identical.
- `repl-window.ts` improved reconnect sequence
   - Use the `NReplEvaluation` class to retrieve error output and display it in the REPL window. Unfortunately with will not show errors on the first connect with shadow-cljs because the repl needs some time to initialize completely and show the error during eval. I the REPL window is closed and reopened the error is shown on reconnect. This is maybe better than nothing. *gg*

calva-error-reconnect

- Added mechanism to add history entries only if they do not already exist.
- Added commands to clear the REPL windows
  - Added a command per REPL type.
  - Clear the history of the REPL window and clear the content in the webview.
- Add robust support for evaluation interruption (ctrl+d  - see #237)
- Added support for `read-line` from the REPL window ( see #377)

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse

### CODE REVIEW

**Comment by cfehse** [comment]
Ping @pez, @kstehn

Just take a look it this changes. If we decide to include this I can break it down into smaller pieces.

**Comment by kstehn** [comment]
I like this when i have more time will look into the code change.
One thing is i would, like you already said, break it down for now i see two pieces directly.
Your main Change and the "clear Command".

For the clear command i think it would be cool if there would be one command that clears the output for the focused repl window.

**Comment by cfehse** [comment]
@kstehn

It would be cool to have a context menu in the webview or to have the ability to reload the webview. I found this solution with two commands the least confusing - at least less confusing compared to the command that currently exists.

**Comment by PEZ** [comment]
Looks very promising! I can say directly that I think this should be done. (Haven't had a look at the source, but saying this with your descriptions as a basis, and knowing that you know what you are doing code-wise 😄 )

Wondering about this:

> * Added commands to clear the REPL windows
>   * Added a command per REPL type.
>   * Clear the history of the REPL window and redisplay it.
>   * Ensure that the REPL windows stays in the same view column and namespace.

Is this that you are making the command for clearing the window more visible? Asking because there already is such a command. Same question regarding the history.

And not sure what is meant by the last bullet there.

**Comment by cfehse** [comment]
The two new commands replace the old command to clear the history of the active REPL window. The new commands are displayed in the nREPL selection (the button in the statusbar) depending on the state.

The commands clear the history and reload the corresponding REPL window (dispose it an show it again). The old command cleared the history and told the user to close and reopen the REPL windows. This is now done in the command.

**Comment by PEZ** [comment]
Another enhancement of the history I wish for is to only add items if they are not exactly the same as the previous one. It might be because I only use the REPL window when testing it, but I often have to go history up many times before getting past all the `1`s. 😄

**Comment by cfehse** [comment]
> Another enhancement of the history I wish for is to only add items if they are not exactly the same as the previous one. It might be because I only use the REPL window when testing it, but I often have to go history up many times before getting past all the 1s

Added that. *gg*

**Comment by cfehse** [comment]
@PEZ  @kstehn @jmingtan

I added an implementation to retrieve user input from the REPL window. Currently the REPL window statically returns a string. This will be fixed in the next iteration.

**Comment by cfehse** [comment]
@PEZ @kstehn @jmingtan

I now finished the `read-line` support for the REPL Window. The behavior should be exactly as in a console repl. Due to this feature I implemented a robust way to interrupt running evaluations in the REPL using `ctrl-d` (see issue #237) - and added a hint to the REPL HTML file.

**Comment by cfehse** [comment]
@PEZ @kstehn

I moved the PR to the upstream repository.

**Pull request closed without merging**
