### PR TITLE
Workaround for paredit's inability to support multiline

### PR DESCRIPTION
**Pull request by JBlaz**
## What has Changed?
- When more than one line is selected use VSCodes default behavior for sexp navigation or selection. This will need to be removed when support is added.

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *You need to sign in/up at Circle CI to find the _Artifacts_ tab.*
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [x] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.

### CODE REVIEW

**Comment by PEZ** [comment]
Thanks for the PR!

I think there are two different cases here:

1. There is some very similar built-in command default bound to the same keys as Paredit's defaults
    * I think this only applies to *Expand Selection* and *Shink Selection* and only on Windows and Linux (on Mac the *Paredit Grow Selection* command is bound to different keys than the built-in command.
2. There is no very similar built-in command and/or it is not default bound to the same keys
    * This applies to all other Paredit Commands that I can think of
    * The PR includes a few of these, but not others.

For category 2 the workaround would disable the command when there are multiple cursors, instead of what happens today that the command applies to the first of the cursors. It's a matter of taste which is preferable.

For category 1, the new behaviour would make more sense. Calva's commands for growing and shrinking the selection work very similar to how VS Code's built-in commands do. It wouldn't be a disablement. The problem is, these commands are category 2 on Mac. We might be able to solve that by splitting the shortcut definition into separate definitions for Mac and Windows/Linux. But that adds complexity and maintenance...

Maybe it does most sense to leave it up to the user to work around this limitation? The Calva documentation could include information about it. Here would be a good place, I think: https://calva.io/paredit/#about-the-keyboard-shortcuts

**Comment by JBlaz** [comment]
Fair enough. Documentation changed for your consideration.

Also, grow and shrink are the same key bindings at least on linux.

**Comment by PEZ** [comment]
This is awesome. Sorry for the radio silence. I have to admit I just dropped the ball. 😢

**Comment by PEZ** [comment]
Many thanks!

**Pull request merged**
