### PR TITLE
Improve clojure lsp integration method

### LINKED ISSUE #913: Improve clojure-lsp jar integration
This is a bit of a brainstorm issue, for now at least. Currently, we don't know what version of clojure-lsp Calva is using since we just package a `clojure-lsp.jar` file in the vsix.

It would be nice if we could use a release tag from the clojure-lsp repo to know what version Calva is using. This tag could either be committed with Calva, but also we could have a default that gets bumped sometimes, but allow the user to change the tag via config.

This starts to get into possibly making Calva download clojure-lsp instead of packaging it with the vsix. Is it possible and reasonable to download and save a file to someone's machine from an extension?

1. User installs the Calva extension
2. Calva checks some location for clojure-lsp (wherever we'd download it to)
3. If it's there and it's the latest version (we can include the release tag in the jar file name), then don't download it, just start clojure-lsp using the existing jar
4. If it isn't there, download it, then start it

Thoughts, @pez?

### PR DESCRIPTION
**Pull request by bpringe**
## What has Changed?

- Calva will now download the clojure-lsp jar according to the version set in `config.ts`
- The jar name will include the version
- Calva will check if a jar for the current version already exists on the file system, and if so it will not download a new one
- If a new jar is downloaded (version was changed since last run), once the download succeeds, any existing clojure-lsp jars besides the one just downloaded will be deleted
- If an error occurs during the jar download, the file system will be searched for existing jars, if any are found, the first one will be used, and a warning will be logged stating the download failed and which jar is currently being used
- If an error occurs during the jar download, and no other clojure-lsp jars are on the file system, an error message will pop up for the user stating there was an issue activating clojure-lsp and advising to check the logs and report any issues found.
- Errors handled include complete request failures as well as responses with a non-200 status (such as if we add an invalid version to the config)

As you can see I'm trying to bullet-proof this stuff :smile:. I almost added a user setting for the version, but that adds more complexity and could cause breakage, confusion, etc. if they change it to some version that Calva doesn't work well with. Basically, there doesn't seem to be good reason to make it a user setting.

Fixes #913 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *There is a CircleCI bug that makes the Artifacts hard to find. Please see [this issue](https://discuss.circleci.com/t/artifacts-tab-not-showing-unless-logged-in/32433) for workarounds.*
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - ~[ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.~
- [x] Created the issue I am fixing/addressing, if it was not present.
- [ ] Added to or updated docs in this branch, if appropriate

## The Calva Team PR Checklist:

Before merging we (at least one of us) have:

- [ ] Made sure the PR is directed at the `dev` branch (unless reasons).
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and tested it there if so.
- [ ] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse, @bpringe

### CODE REVIEW

**Comment by bpringe** [comment]
I plan to test this on Windows as well, tomororw.

**Comment by bpringe** [comment]
Note to self: need to update docs before merging.

**Comment by bpringe** [comment]
Well... scratch this version I think... I'm noticing the added complexity and possible issues are not worth it, compared to just including the jar in the vsix. Besides all the download logic and error checking, I realized (and experienced) if the download fails before it's complete, the file will exist but will be corrupt. So then it won't be re-downloaded, because it exists, but the existing one is corrupt so it won't start.

Thinking we can just slightly improve the existing method by downloading a specific version and versioning the jar, but leave it at that, at least for now. There are more important things to tackle right now anyway.

**Comment by PEZ** [comment]
It was there. Then it wasn't. 😄 Probably a good call if you experienced that friction. And starting simple is seldom wrong.

**Pull request closed without merging**
