### PR TITLE
Fix regexp tets function according to latest changes of the indention rules sorting

### LINKED ISSUE #2032: Indenter and formatter not in agreement about some forms
With a form like (cursor at `|`):

```clojure
(and x |y)
```

Pressing <kbd>enter</kbd> gives

```clojure
(and x 
     |y)
```

Which I think is expected (can't recall right now). However, if I then press <kbd>tab</kbd>, I get:

```clojure
(and x
  |y)
```

So it seems like the indenter and the formatter read the config differently.

Possibly related:

> That said, I am experiencing weird indentation issues quite often lately. Which could be regressions from the fixing of this issue. I'll try figure out a repro. It happens to me in my work project and code I can't share as is.

_Originally posted by @PEZ in https://github.com/BetterThanTomorrow/calva/issues/1957#issuecomment-1398981754_

### PR DESCRIPTION
**Pull request by SillyCoon**
## What has changed?

Fixes #2032

If this PR involves code changes, I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
  - [x] Smoke tested the extension as such.
  - [x] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
  - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
  - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Comment by SillyCoon** [comment]
Hello @PEZ! I found a nasty issue, it seems that after the datastructure change to passs ordered list as a ruleset for indenter, now cljs compiler can correctly convert clojure regexps to js and not just stringify it, so I guess the best solution is to allow use both js and clj styles of regexps in the code. I've adjusted the comparing function and wrote the unit test for it. So I guess all strange behaviour should be fixed with this PR.

**Review by PEZ — COMMENTED** [review]
This is beautiful.

Do you think it's possible to create some tests that explicitly check that the indenter and the formatter agree, given the same form, position and config?

**Comment by PEZ** [comment]
In clojure-lsp configs the regexes are expressed using a reader tagged string `#re "regex"`. I didn't test that when testing this PR (because I forgot). But it is probably something we should have tests for as well.

**Comment by SillyCoon** [comment]
> This is beautiful.
> 
> Do you think it's possible to create some tests that explicitly check that the indenter and the formatter agree, given the same form, position and config?

Oh, I guess I can add these tests together with the `paredit backspace` as well, I guess they should behave the same in the similar situation. I will do it in the next PR with fix #2038

**Pull request merged**
