### PR TITLE
Centralized compiled files/packages and reorganized the webview sources.

### PR DESCRIPTION
**Pull request by cfehse**
**PROPOSAL**

This is the second half of the work I did on the build system/source tree. This is quite a mouthfull. I centralized all compiles files into the `out` directory (calva extension, webview package and cljs-lib). I moved all static files from `html` into subdirectories under `assets`. The build process is not changed only from where the files will be packaged respectively where they are compiled to.  
I changed the the location of the webview sources:
- `calva/webview-src/client/**` now live in `calva/webview`
- `calva/webview-src/server/main.ts` is now `calva/webview.ts` (to correspond with the compiled location `out/webview.js`)
- `tsconfig.json` for the webview is now `calva/webview/tsconfig.json` (and will there be used by `webpack.config.js`)

I moved the output directory for the compiled `cljs-lib` from `out/cljs-lib` respectively  `out/cljs-lib/test`. There are no functional changes only changed `import` / `require` statements for the new locations of the files and changes in `repl-window.ts` to reflect the new directories. I removed the `html`directory from the whitelist in the `.vscodeignore` file because it is no longer needed. All moving parts of the extension are now in `out` or in `asset`.

Take a very close look - the software passed my CI mockup scripts and the vsix works under Windows or Linux. But if you think the changes are to big then it's alright with me if you do not merge it.

Thanks!

Tested on following platform(s):
- [x] Windows
- [x] Linux
- [ ] macOS

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [ ] Referenced the issue I am fixing/addressing.
     - [ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [ ] Created the issue I am fixing/addressing, if it was not present.
- [ ] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

Ping: @pez, @kstehn

### CODE REVIEW

**Comment by cfehse** [comment]
@PEZ I hit the wrong key. IT is not ready yet!

**Comment by cfehse** [comment]
Ping: @PEZ, @kstehn Now all information should be included.

**Comment by kstehn** [comment]
I like this :)
Makes it simpler to know what is in which directory 
And as far as i can tell, all the changes are pretty localy (webview, and where things gets compiled)

**Comment by PEZ** [comment]
I haven't had a look at the code changes yet, but from the description I am totally for it. This is making things make much more sense when having a first look at the repository, I think.

@kstehn , if the six packages built locally and on Circle CI work, then I'm voting for merging this in, and you're welcome to do it, if you agree.

**Pull request merged**
