### PR TITLE
Jack in support for the Basilisp language

### LINKED ISSUE #2559: jack-in support for the Basilisp programming language
`jack-in` support for the [Basilisp ](https://github.com/basilisp-lang/basilisp) Clojure compatible dialect implemented in Python.

I'll follow up with a PR.

### PR DESCRIPTION
**Pull request by ikappaki**
## What has changed?

- Jack in support for the [Basilisp ](https://github.com/basilisp-lang/basilisp) programming language. Tested on Linux, MS-Windows and MacOs, also added an integration test. Added documentation. I followed nbb as an example, thus the new entries are in close proximity with each other. I've also introduced a new `baslispPath` config option.
- Fixed a bug in project-root.ts to account for platform dependent path separator, discovered while running the integration tests on MS-Windows.

Fixes #2559 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Comment by PEZ** [comment]
Hi! Thanks for helping with Calva! 🙏 

I'm not sure what it takes to test this. Can you provide some instructions for someone that knows nothing at all about Basilisp and whose Python experience is from decades ago?

It's great with an integration test, but it adds a dependency requirement to anyone who runs the tests, and I don't think we can allow us to do that. So I think the test needs to be resilient on Python and/or Basilisp missing and not run the test in that case. For CI we could consider installing it, if it doesn't add too much time to the runs.

**Comment by PEZ** [comment]
For the basilisp path config: Do we need it? We do not have configs for `clojure` or `lein` paths for instance. Instead we require that those are on the user's PATH.

**Comment by ikappaki** [comment]
> Hi! Thanks for helping with Calva! 🙏
> 
> I'm not sure what it takes to test this. Can you provide some instructions for someone that knows nothing at all about Basilisp and whose Python experience is from decades ago?

HI @PEZ,

To test locally, you need to have Python versions 3.8 to 3.12 installed. Use the Python package manager `pip` to install Basilisp. Once installed, you can start the REPL or nREPL server from the command line. After that, everything is Clojure, and no additional Python knowledge is required except for interoperability with the Python runtime. For more info see the [Basilisp Documentation](https://basilisp.readthedocs.io/en/latest/), and some [example notebooks](https://github.com/ikappaki/basilisp-kernel/tree/main/notebooks) that showcase interop with Python.

```shell
$ <install python>
$ pip install bassilisp 
# ...
$ basilisp repl 
basilisp.user=> (require '[clojure.string :as str])
nil
basilisp.user=> (str/replace "abc" "b" "x")
"axc"
^C
$ basilisp nrepl-server
nREPL server started on port 49640 on host 127.0.0.1 - nrepl://127.0.0.1:49640
```

Basilisp code files use the `.lpy` extension. To "jack in" to a project with Calva, ensure that there is an empty `basilisp.edn` file at the root of the project (similar to `deps.edn`).

> 
> It's great with an integration test, but it adds a dependency requirement to anyone who runs the tests, and I don't think we can allow us to do that. So I think the test needs to be resilient on Python and/or Basilisp missing and not run the test in that case. For CI we could consider installing it, if it doesn't add too much time to the runs.

I'll make the test conditional on the `basilisp` executable being in the PATH or running on CI. The CI reports that it takes 20 seconds to install Python and Basilisp, and another 14 seconds to run the jack-in test, which I think is acceptable for integration testing. Running the Basilisp jack-in test is very fast, but it requires compiling the Python files the first time it is executed. 

thanks

**Comment by PEZ** [comment]
I have now tested both jack-in and connect. Works like a charm.

**Comment by ikappaki** [comment]
> For the basilisp path config: Do we need it? We do not have configs for `clojure` or `lein` paths for instance. Instead we require that those are on the user's PATH.

Unfortunately, I can't think of better way to support Python virtual environments. Python uses virtual environments to create isolated directories containing pristine copies of a Python installation. For example, you can create a virtual environment in a directory like `a/path/to/virtenv`, activate the virtual environment, and then install Basilisp there. The directory where Basilisp is installed within the virtual environment is not in the global PATH. If we need to refer to this installation from Calva (to choose the virtual environment), it can be done via a configuration option.

It's very common to have one or more Python virtual environments installed, and we need a way to specify which one to use in Calva for Basilisp.

Another idea is to use the VS Code Python extension to let the user choose the virtual environment they want. The extension provides a command to select the Python interpreter to the virtual environment. However, this approach requires the Python extension to be installed and for Calva to interface with it. I initially tried this method but couldn't successfully retrieve the value—it’s not straightforward to do, and could be confusing having the user to use that extension.

**Comment by PEZ** [comment]
Let's go with the basilispPath config then.

And let's try with adding the integration test to CI. If we deem it to take too much time from the feedback-loop we can remove it later.

Another thing. In the `test-data` directory there are some projects for different scenarios. You could add a `minimal-basilisk` project there and make it as minimal as just an empty `basilisk.edn`, or a tad less minimal than that. This way it is straightforward to make things like sanity checks of the integration (jack-in/connect support).

**Comment by ikappaki** [comment]
> And let's try with adding the integration test to CI. If we deem it to take too much time from the feedback-loop we can remove it later.
> 
> Another thing. In the `test-data` directory there are some projects for different scenarios. You could add a `minimal-basilisk` project there and make it as minimal as just an empty `basilisk.edn`, or a tad less minimal than that. This way it is straightforward to make things like sanity checks of the integration (jack-in/connect support).

I've tried to address review comments with latest commits, extract from CI:

```
Integration testing, Jack-in: start repl and connect (jack-in) to Basilisp
Integration testing, Jack-in: Basilisp executable found at /home/circleci/.local/bin/basilisp
Settings written to /home/circleci/calva/test-data/.vscode/settings.json
[2650:0602/163133.308061:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2650:0602/163133.524281:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Integration testing, Jack-in: ../projects/minimal-basilisp/src/test.lpy opened for project type basilisp
Jack-in process kill requested
Jack-in terminal killProcess(): Closing any ongoing stdin event
Jack-in terminal killProcess(): Killing process using tree-kill
Jack-in process kill requested
Jack-in terminal killProcess(): Closing any ongoing stdin event
Jack-in terminal killProcess(): Killing process using tree-kill
Integration testing, Jack-in: waiting for connect...
Socket closed false
[2650:0602/163134.415966:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Integration testing, Jack-in: waiting for connect...
[2650:0602/163147.058981:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Integration testing, Jack-in: connected to repl
Integration testing, Jack-in: opened test.clj document again
Integration testing, Jack-in: test.lpy closed for Basilisp
    ✔ start repl and connect (jack-in) to Basilisp (14362ms)
```

**Comment by PEZ** [comment]
I don't quite understand why the CI pipeline is not running on this PR. Will try see if I can figure that out...

**Comment by ikappaki** [comment]
> I don't quite understand why the CI pipeline is not running on this PR. Will try see if I can figure that out...

Indeed, I can't see anything suspicious with this PR. My fork's run for the same is at https://app.circleci.com/pipelines/github/ikappaki/calva/21/workflows/297663e1-16d7-4e29-a333-854a90048f9f

**Comment by PEZ** [comment]
Hmmm, I don't get it. Will merge it to `dev` since it looks good and you obviously see it running in CI, and passing, @ikappaki. Let's see if merging it to `dev` triggers the pipeline in the BetterThanTomorrow org.

**Comment by PEZ** [comment]
Yeah, https://app.circleci.com/pipelines/github/BetterThanTomorrow/calva/7938/workflows/84ced8f0-548b-4542-aa6d-053a0947e721

Very strange. I checked the settings on CircleCI and they still say to run on PRs from forks...

**Comment by ikappaki** [comment]
> Yeah, https://app.circleci.com/pipelines/github/BetterThanTomorrow/calva/7938/workflows/84ced8f0-548b-4542-aa6d-053a0947e721
> 
> Very strange. I checked the settings on CircleCI and they still say to run on PRs from forks...

Perhaps worth raising a question with CI about it?

Thanks for merging!

**Pull request merged**
