### PR TITLE
Add command to open clojure lsp log file

### LINKED ISSUE #1362: Add command to open the clojure-lsp log file
This was mentioned here: https://github.com/BetterThanTomorrow/calva/issues/1350#issuecomment-950052069

### PR DESCRIPTION
**Pull request by bpringe**
## What has Changed?

- Added a command to open the clojure-lsp log file - `Calva Diagnostics: Open Clojure-lsp Log File`
- This is implemented by getting the log file name from clojure-lsp's server-info command, so if clojure-lsp is failing to start, this command will not work.

TODO:
- Test on:
  - [ ] Windows
  - [x] Linux
  - [x] MacOS
- [x] Make the command show a message that the server isn't started if it's not, like the server info command does. We could also make it not show in the menu when the server isn't started, but I like the former approach since this is a diagnostic tool, and no one will wonder why the command isn't showing up when the server is failing to start.

Closes #1362 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. NB: *You need to sign in/up at Circle CI to find the _Artifacts_ tab.*
     - [x] Tested the particular change
     - [x] Figured if the change might have some side effects and tested those as well.
     - [x] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [x] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.

Ping @pez, @bpringe

### CODE REVIEW

**Comment by bpringe** [comment]
@ericdallo Is there a way we can get the log file path without the server running, such as in cases when there is an error during initialization, and the server-info command can't be used?

**Comment by ericdallo** [comment]
@bpringe unfortunately, there is not as the oath is generated by JVM in it's temp folder which may vary from OS to OS.

**Comment by bpringe** [comment]
I guess this command will still be helpful, at least in some cases, right?

**Comment by bpringe** [comment]
@PEZ Can you test this on Windows?

**Comment by PEZ** [comment]
I haven't tested on Windows. My Windows machine is acting up on me. However, the code looks good and I doubt there is anything that even Windows can do to make troubles (famous last words). We'll find out if there is a problem, I think.

**Pull request merged**
