### PR TITLE
add circleci for publishing a preview version

### PR DESCRIPTION
**Pull request by Cyrik**
## What has Changed?

- added `marketplace-preview-publish` job to circle-ci

VSCode recently added pre-release versions of extensions. This would be great for our dev branch. The (docs)[https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions]

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [ ] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Added to or updated docs in this branch, if appropriate
- [ ] Tests
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
     - [ ] Tested the VSIX built from the PR (so, after you've submitted the PR). You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test.
- [ ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [ ] Created the issue I am fixing/addressing, if it was not present.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) or run `npm run eslint`).

Ping @pez, @bpringe

### CODE REVIEW

**Comment by Cyrik** [comment]
I'm not well versed in circleci configs and I don't fully understand your setup, but I think this should work?

**Comment by PEZ** [comment]
I think it will work. Pretty exciting stuff!

**Comment by PEZ** [comment]
Well, something went wrong. 

image

https://app.circleci.com/pipelines/github/BetterThanTomorrow/calva/4448/workflows/323885d4-341d-4c66-9145-249c58c45e7e/jobs/18121

```
 ERROR  Cannot use '--pre-release' flag with a package that was not packaged as pre-release. Please package it using the '--pre-release' flag and publish again.
```

Maybe this job shouldn't run in the release workflow? Seems better to wait until after this workflow when dev version is bumped.

**Comment by PEZ** [comment]
However, that workflow isn't being run from this bump: 

image

I wonder what's up with that? You have any ideas, @bpringe ?

**Comment by Cyrik** [comment]
@PEZ Yeah this shouldn't run on release, it should run on merge into dev, but I'm not sure how to do that in your flow 😅

**Comment by PEZ** [comment]
Almost there!

image

Fails because the marketplace does not support semver pre-release tags:

image

There's an issue about it here: https://github.com/microsoft/vsmarketplace/issues/310

I'm disabling it for now, like so:

image

Let's keep track of that issue. Hopefully they'll come to their senses about this. Otherwise, maybe we can use  murmurmhash3 to create a number from our tag.

**Comment by Cyrik** [comment]
Ah interesting about the semver. I saw it mentioned in the docs already. I thought they "don't support it" in the sense of: we don't handle them as special, not that they just blow up...

**Comment by PEZ** [comment]
Tracking this issue here now, btw: https://github.com/BetterThanTomorrow/calva/issues/1554

**Comment by bpringe** [comment]
> However, that workflow isn't being run from this bump

@PEZ  The bump adds "[skip ci]" to the commit message to skip that workflow. Does that answer your question or was it about something else?

**Pull request merged**
