### PR TITLE
Paredit - Introduce killLeft

### LINKED ISSUE #2426: Feature Suggestion - Paredit - Kill Left equivalent to Kill Right

### PR DESCRIPTION
**Pull request by riotrah**
## What has changed?

This PR depends on (is branched off of) #2425 - but doesn't have to be. Merging this will effectively implement multicursor movement and selection.

This PR introduces a `killLeft` equivalent to `killRight`. I use `killRight` a hundred times a day, and often wish for a `killLeft` - for now I've settled on binding `ctrl+h` to kill the left sexp, but it isn't quite the same.

`killLeft` naturally has some different semantics to `killRight`, for example, how it doesn't have to deal with comments with as much care as `killRight`. As such, the code is a little different, but largely identical, just in the other direction. The best way to see what behavior I envision for `killLeft`, please see the unit tests, as they should capture all the nuances.

Other changes:

- **add more descriptive paredit test names** -> eg, add `backwardSexpRange` to the test suite name for `rangeToSexprBackward` for easier grepping.
- **Add more windows tests for `killRight`**, and fix them with some platform-agnostic-line-ending handling changes.
- **Add default binding** for `killLeft` to `ctrl+h`
- **Add paredit docsite entry with missing gif link** - shall I record a usage gif, get rid of the entry, or will you record one?

Fixes #2426

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
    - [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
        - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
        - [x] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [x] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [x] Figured if the change might have some side effects and tested those as well.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Comment by PEZ** [comment]
Very cool command that I didn't know I was missing. Thanks for providing! 🙏 

Since I don't know exactly what to expect... a thing that surprised me a bit is that killing left from the start of a line does not kill the whitespace between the cursor and the end of the previous line. Consider this document:

```clojure
(a• |b)
```

<kbd>kill left</kbd>

```clojure
(a• |b)
```

I.e. it doesn't do anything. The (to me) corresponding case with **Kill Right** behaves like so:

```clojure
(a|• b)
```

<kbd>kill right</kbd>

```clojure
(a| b)
```

Am I expecting the wrong thing or is it a bug?

**Comment by riotrah** [comment]
Yep, it's a bug, thanks for catching!

**Comment by riotrah** [comment]
Oh wait I may have misunderstood

**Comment by riotrah** [comment]
Here's what I think:

1. Cursor is _not_ at newline/linestart
```clj
(a• |b)
```
`killLeft`:
```clj
(a•|b)
```
To me, the equivalent `killRight` example:
```clj
(a| •b)
```
`killRight`:
```clj
(a|•b)
```
---
2. Cursor _is_ at newline/linestart
```clj
(a•| b)
```
`killLeft`:
```clj
(a| b)
```
To me, the equivalent `killRight` example:
```clj
(a |•b)
```
`killRight`:
```clj
(a |b)
```


Ie, if at a newline, then kill the newline and only the newline, unless there's whitespace to squash, in which case, squash it.

Otherwise, if not at newline (but still in whitespace), kill whitespace until newline/linestart.

**Comment by riotrah** [comment]
Ah, but reading your comment yet again, you still point out a bug, the killLeft should at least kill the whitespace after the newline/linestart, even if it doesn't kill the newline itself

**Comment by PEZ** [comment]
Looks like we are close to go with this, right? The documentation is not building, but by the look of the log, it is easy to fix.

**Comment by riotrah** [comment]
@PEZ oh yes, the killLeft gif. Do you want me to record it? my theme does not look much like yours, so if you want the consistent look, let me know what theme you're using, or lmk if you want to do it yourself, or, if you don't care if it matches the other gifs, I can do it anyways.

Finally, if you think it's fine without the gif or entry in that table, lmk.

**Comment by PEZ** [comment]
> the killLeft gif. Do you want me to record it?

I can do it, but it will have to wait to later tonight. If you get to it before me:
* Theme **Solarized Light** (no, I'm not using that theme, it just looked good for that page, me thinks)
* Tool I used: GIF Brewery (maybe it is a Mac only thing)

I think we should add it. We have one for every ParEdit command so far, I think. At least we have one for KillRight.

**Comment by riotrah** [comment]
Gif brewery is so old/deprecated/delisted it hangs the Mac App Store with an infinite loop of "This app is not available in your region" hahaha.

**Comment by riotrah** [comment]
kill-left

**Comment by PEZ** [comment]
I downloaded GIF Brewery 3 from some gif site long time ago, still works and still is the best tool I know for these jobs. 😄 Pretty gif there, I think whatever you use looks like it will work too.

In your gif, though, there are some places where it looks like kill-left is not working. I think you are moving the cursor with the arrow keys or something. Imo it's better if the gif only shows kill-left. Something like so:

68CE9727-5EE1-4ECB-B05E-6094338FBA80-34632-000524CE6F484F10

**Comment by PEZ** [comment]
That gif I made also reminds us that we need to fix how we let line comments break the document structure. Generally in Paredit, not specifically for this command.

Another thing is how we handle the undo stack. Now if we do a series of kill-left (or kill-right for that matter) and then undo, the whole series is undone. Only the last one should be undone.

**Comment by PEZ** [comment]
Anyhoo! This is good for merging. We can fix the GIF in a follow-up doc-PR.

Many thanks for adding this command! 🙏 I think I will be using it quite a lot!

**Comment by riotrah** [comment]
Weird-ish that the kills are considered atomic. I've noticed this for other types of vscode editing even outside of calva/clojure starting some point like maybe 6 months or so ago. I used to get hyper-granular (ie, every single edit) undos, but now they're like batched, which is annoying.

Anyways, either this is something extension authors can control, something in the user settings for all of vsc, or both, so I can explore this next.

**Comment by PEZ** [comment]
We add undo points for our edits, I think we just miss to do it for killRight, killLeft and some other commands.

**Pull request merged**
