### PR TITLE
Trim result decoration

### LINKED ISSUE #2617: Result decorator fails to display error message for compiler exceptions starting with an empty line
Hi,

the result decorator that appears next to an evaluated form in the editor is intended to display the result or error of the evaluation. However, in certain cases, it may display nothing next to the `=>` symbol.
image

For example, with Basilisp, this issue occurs when a compiler exception is thrown during evaluation. In the screenshot above, the issue arises when trying to call an unbound `abc` symbol. This happens because the exception message starts with an empty line, and the decorator only displays the first line of the error.

The expected behavior is for the result decorator to show the most important information about the error. If that's not possible, it should at least display the first meaningful line. In this case, since the exception starts with an empty line, the decorator should skip that and display the first line containing actual text.

To reproduce
1. Install [Basilisp](https://github.com/basilisp-lang/basilisp) in a new Python virtual environment and activate it.
2. In a new empty project dir, create a `user.lpy` file  containing an `(abc)` form, which will throw a compiler exception
```user.lpy
(ns user)

(abc)
```
3. Add an empty `basilisp.edn` file to the project root.
4. Start the Basilisp nREPL server
```bash
(venv-project) project> basilisp nrepl-server
nREPL server started on port 62695 on host 127.0.0.1 - nrepl://127.0.0.1:62695
```
5. Open the project folder with Calva, open the `user.lpy` file, and connect to the nREPL server via `REPL` -> `Connect to a running REPL in your project` -> `basilisp`.
6. In  the `user.lpy` tab, evaluate `abc`. You'll notice that an empty `=>` is displayed next to the form, where an exception message should appear.

In the output.calva-repl, the full exception message is displayed fine
```clojure
; 
;   exception: <class 'basilisp.lang.compiler.exception.CompilerException'>
;       phase: :analyzing
;     message: unable to resolve symbol 'abc' in this context
;        form: abc
;    location: d:\bas\project\user.lpy:1
;     context:
; 
;  1 > | (ns user)
;  2   | 
;  3   | (abc)
```

PR to follow.

### PR DESCRIPTION
**Pull request by ikappaki**
Hi,

could you please review patch to trim the beginning of the result decoration so that the first line with text is displayed instead. It fixes #2617.

## What has changed?

The patch trims leading whitespace so that the first non-empty line is displayed in the inline results decorator, avoiding any empty display if the result starts with spaces.

The Basilisp compiler exception mentioned in the #2617 issue is now reported

image

While the fix itself is straightforward, I noticed that the `annotations` package lacked tests, so I took the opportunity to create the first test for it.

The actual issue requires GUI testing, but I couldn't find an existing GUI framework in the codebase or online to test GUI components like decorators in VSCode (I might have missed it).

Therefore, I installed two npm packages to assist me with it

1. [sinonjs](https://sinonjs.org/): To spy on the TextEditor and verify that the setDecorations call arguments do not contain leading whitespace.
2. [screenshot-desktop](https://github.com/bencevans/screenshot-desktop): To capture screenshots of the application for manual inspection of the GUI component.

This allowed me to write a test to confirm that the correct text is passed to the decoration and manually inspect the results.

I also updated the CircleCI configuration to store the screenshots as artifacts for inspection.

For example, here is a screenshot taken from the CircleCi generated artifacts before the fix, showing the empty inline decoration:

setDecorations-before

And here is a screenshot after the fix, showing messages truncated to display the first non-empty line:

https://output.circle-artifacts.com/output/job/a360e400-f757-4de0-8913-acf154e49e86/artifacts/0/integration-screenshots/Annotations/decorateResults-empty-1st-line.png

decorateResults-empty-1st-line

I understand that this addition to the test suite may be significant, but I believe it adds substantial value.

Please let me know if you would like me to:

1. Proceed with this GUI testing framework and include references in the documentation (noting the need for [imagemagick ](https://imagemagick.org/index.php) on Linux).
2. Split this into another PR.
3. Remove it and only keep the main change.

Thanks

Fixes #2617 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I have changed the PR base branch, so that it is not `published`. (Sorry for the nagging.)
- [x] Made sure there is an issue registered with a clear problem statement that this PR addresses, (created the issue if it was not present).
    - [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.
- [ ] Figured if **anything** about the fix warrants tests on Mac/Linux/Windows/Remote/Whatever, and either tested it there if so, or mentioned it in the PR.
- [ ] Added to or updated docs in this branch, if appropriate
- [x] Tests
  - [x] Tested the particular change
  - [ ] Figured if the change might have some side effects and tested those as well.
- [x] Formatted all JavaScript and TypeScript code that was changed. (use the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or run `npm run prettier-format`)
- [x] Confirmed that there are no linter warnings or errors (use the [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), run `npm run eslint` before creating your PR, or run `npm run eslint-watch` to eslint as you go).

Ping @pez, @bpringe, @corasaurus-hex, @Cyrik

### CODE REVIEW

**Comment by ikappaki** [comment]
Hi, just checking if you need any clarification on the issue, fix, or tests. I haven't heard back, and you're usually quick with PR feedback, so I’m wondering if something’s missing.

The fix is simple—just trimming the white-spaces at the front of the result—but let me know if you have any concerns about the issue or testing dependencies. I'm flexible and can revise or even discard the whole thing if you think the problem might be server-side.

Thanks

**Comment by PEZ** [comment]
> I haven't heard back, and you're usually quick with PR feedback, so I’m wondering if something’s missing.

Hi! I'm sorry. Didn't see this PR. Now will check. By the description of the change things look great. BRB!

**Comment by PEZ** [comment]
Wow. Thanks! And extra thanks for adding that test! 🙏 ❤️ I didn't even know these kind of facilities existed. 🤯 You are most welcome to add documentation about it to the wiki.

Things look good except one thing: We can't go ahead with the way you updated the Circle-CI configuration. The `.circleci/config.yaml` file should not be updated manually. It is built using [YAMLScript](https://yamlscript.org/). There's a Babashka task for it in the `.circleci` directory. Usually it is very straightforward; you probably just need to move your changes to an existing or now file in the `.circleci/jobs` directory (and update `config.ys` if you create a new jobs file).

**Comment by PEZ** [comment]
I don't understand why the CircleCI job is not run for this PR. That I must fix ASAP!

**Comment by ikappaki** [comment]
> You are most welcome to add documentation about it to the wiki.

Thanks, I initially thought I needed to add it to the Calva docs, but it turns out I need to update the GitHub wiki instead. I can do this afterwards.

> Things look good except one thing: We can't go ahead with the way you updated the Circle-CI configuration. The `.circleci/config.yaml` file should not be updated manually. It is built using [YAMLScript](https://yamlscript.org/). There's a Babashka task for it in the `.circleci` directory. Usually it is very straightforward; you probably just need to move your changes to an existing or now file in the `.circleci/jobs` directory (and update `config.ys` if you create a new jobs file).

I updated `.circleci/jobs/test-integration.yaml` and ran `make build` to regenerate `.circleci/config.yml` (which was unchanged from my previous checkin). I couldn't fit the `store_artifacts` command into the existing `store` definition below because it requires both `path` and `destination` parameters, so I left it as is. Let me know if you'd like me to try fitting it in (I'm not familiar with YAMLScript).

```ys
defn store(pair):
  type =: pair.keys().0
  path =: pair.vals().0
  =>::
    ! "store_$type":
      path:: path
```

I also re-based the branch from `dev` latest.

**Comment by ikappaki** [comment]
> I don't understand why the CircleCI job is not run for this PR. That I must fix ASAP!

I think we're hitting a strange CircleCI policy:

https://support.circleci.com/hc/en-us/articles/360008097173-Troubleshooting-why-pull-requests-are-not-triggering-jobs-on-my-organization

> ## If you're following the fork instead of the upstream repo
>
> A user who submits a pull request to your repository from a fork, but no pipeline is triggered with the pull request. This can happen when the user is following the project fork on their personal account rather than the project itself on CircleCI.
> 
> This will cause the jobs to trigger under the user's personal account. If the user is following a fork of the repository on CircleCI, we will only build on that fork and not the parent, so the parent’s PR will not get status updates. 
> 
> In these cases, the user unfollows their fork of the project on CircleCI. This will trigger their jobs to run under the organization when they submit pull requests. Those users can optionally follow the source project if they wish to see the pipelines.
> 
> Note: This feature is not currently supported for BitBucket users.

It seems that since I'm following CircleCI builds on my fork, the build is triggered on my account instead of here. While it's all green on my fork https://app.circleci.com/pipelines/github/ikappaki/calva/35/workflows/28f72872-5329-49ca-adaa-4d6446ba22e8, it's not reported here.

However, I still want my own CircleCI builds during development, so this setup feels odd. It seems I'll need to 'unfollow' my fork on CircleCI before submitting a PR ... 🥲

**Comment by PEZ** [comment]
> I couldn't fit the `store_artifacts` command into the existing `store` definition below because it requires both `path` and `destination` parameters

I think it's perfect as you did it.

**Comment by PEZ** [comment]
Great that you figured out about the PR builds missing. I can understand that they want to save compute, but seems this could be solved by showing the runs from your fork in the Calva org UI, or something, once the PR is active. We can add something about it to the wiki.

Anyway, I can see the greenness at your fork.

**Review by PEZ — APPROVED** [review]
LGTM! Thanks! 🙏

**Pull request merged**
