### PR TITLE
Fix floating promises

### LINKED ISSUE #411: TS-linting warnings about floating promises
While I'm hacking Calva my ts-lister is showing warnings about floating promises on function calls of `evaluateSelection` in `src/evaluate.ts`.

Here is one of them
https://github.com/BetterThanTomorrow/calva/blob/9193fd9a09222174e3848ed4e2584cabba5856c3/src/evaluate.ts#L120

### PR DESCRIPTION
**Pull request by sauvala**
## What has Changed?

- The promise returned by `evaluateSelection` was not handled correctly. Now the function calls are wrapped with `async/await`.

Fixes #411 

## My Calva PR Checklist

I have:

- [x] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.) You'll find the artifacts by clicking _Show all checks_ in the CI section of the PR page, and then _Details_ on the `ci/circleci: build` test. (For now you'll need to opt in to the CircleCI _New Experience_ UI to see the Artifacts tab, because bug.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [x] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
     - [x] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
     - [ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
- [x] Created the issue I am fixing/addressing, if it was not present.
- [x] Updated the `[Unreleased]` entry in `CHANGELOG.md`, linking the issue(s) that the PR is addressing.

## The Calva TEAM PR Checklist:

Before merging we (at least one of us) have:

- [x] Made sure the PR is directed at the `dev` branch (unless reasons).
- [x] Read the source changes.
- [ ] Given feedback and guidance on source changes, if needed. (Please consider noting extra nice stuff as well.)
- [ ] Tested the VSIX built from the PR (well, if this is a PR that changes the source code.)
     - [ ] Tested the particular change
     - [ ] Figured if the change might have some side effects and tested those as well.
     - [ ] Smoke tested the extension as such.
- [ ] If need be, had a chat within the team about particular changes.

Ping @pez, @kstehn, @cfehse

### CODE REVIEW

**Comment by PEZ** [comment]
Hello, 

I'm super happy that you have started sending PRs!

The changes look good. But you have based them on a pretty old (in Calva time) version of `dev`. Can you update your branch from latest `dev`. I tried it and an everything merges cleanly, except `CHANGELOG.md`, but that should be really easy to fix manually.

In case merging upstream is new to you, here is what I would do, with your feature branch checked out:

```sh
git remote add upstream git@github.com:BetterThanTomorrow/calva.git
git fetch upstream
git merge upstream/dev
```

**Comment by cfehse** [comment]
@kstehn  @PEZ  @sauvala 

A question for the Typescript fans and about tackling this kind of linter warnings in general. I am not a fan of changing the method/function signature to `asyn` and placing an `await` before the call in question because this may often not be what was intended and may lead to other warning in code calling the now `async` functions. The functions mentioned in this PR honestly do not need to be `async`. They only start the called functions of and exit (these are command functions). I fix similar warning in the following way:

``` 
function evaluateTopLevelForm(document = {}, options = {}) {
    evaluateSelection(document, Object.assign({}, options, { topLevel: true, pprint: state.config().pprint })).catch(() => {});
}
```
The reject handler should prevent the code from exception being throw because the rejection is not handled as well - the calling code does not care about any rejection anyway. 

What's your opinion about this?

**Comment by cfehse** [comment]
And if you take a look at the `evaluateSelection()` function there are as well two `await` statements in that function because it is easier to write that code synchronously. This all lead to `async`s bubble up all the way in the calling sequence where it is not necessary I think.

**Comment by PEZ** [comment]
I'm not knowledgeable enough about these promise warnings. I was surprised that async/await would silence them. Agree that if we don't need it to be async, for async reasons, we probably shouldn't make it look like it is needed. Can the warning be dealt with using `.catch()` on the promise instead?

**Comment by cfehse** [comment]
@PEZ

Yes it can.

**Comment by cfehse** [comment]
The warning is generally very useful but we often use promises in a "fire and forget" sense so we do not care about the results in the calling/creating code. In this situations the warning is not very useful I think.

**Comment by PEZ** [comment]
I'm pretty fond of the warnings. 😄 

This spring I had serious struggles releasing Calva 2, much because of dangling promises. I was saved by a PR that enabled the warnings. It helped me chase the bugs down. I suggest we are explicit with the ”fire and forget” by adding no-op `.catch()` to them. Maybe even add a comment in them saying that we are not interested in handling whatever error.

**Comment by cfehse** [comment]
And avoid as much `await`s as possible. Because they very often cause serious trouble - like in the case of "allow user input from the REPL window" solution.

**Comment by sauvala** [comment]
@PEZ thanks for noticing that! I'll update my branch.

@cfehse I'm okay for changing the method signature back to non-async and adding the `.catch(() => {})` handler for it instead. Do you think we could also add logging inside the `catch`-statement to see what was the error? I'm not sure if it's really helpful on the VSCode. Does Calva users see those error's somewhere in the console and could report them?

> I am not a fan of changing the method/function signature to asyn and placing an await before the call in question because this may often not be what was intended and may lead to other warning in code calling the now async functions.

Those methods are called from places where  we can use async-functions. If you think there is going to be other use cases for these in the future where you cannot use async-functions, I do the change back to non-async. 🙂 

The `await` functions can also be wrapped inside `try-catch` to enable logging and error handling.

**Comment by PEZ** [comment]
>  Do you think we could also add logging inside the catch-statement to see what was the error? I'm not sure if it's really helpful on the VSCode. Does Calva users see those error's somewhere in the console and could report them?

Yes, these are printed in the dev console, which the user can open and report to us about. We could make it a convention to do:
```
.catch(e => { console.warn(`Unhandled error: ${e.message}`) }`
```
or some such, in these cases.

**Comment by sauvala** [comment]
Opened a new PR that has clean history

**Pull request closed without merging**
